In [13]:
import pandas as pd
import numpy as np
import stat
import re
import warnings
warnings.filterwarnings("ignore")

In [14]:
#cd 'cleaning'

In [19]:
#analysis = pd.read_csv("FF_HEALTH_DC3_ANALYSIS.csv")
roster = pd.read_csv("E29_CHECKIN04_ROSTER_V2.CSV")
dictionary = pd.read_csv("E29_CHECKIN04_QUESTION_DICTIONARY.csv")
raw = pd.read_csv("E29_CHECKIN04_RAW_V1.csv")

full_cleaned_data = pd.read_csv("full_cleaned.csv")

In [20]:
full_cleaned_data

,Unnamed: 0,Email,TeamNumber,TeammateNumber,RecipientEmail,RecipientLastName,RecipientFirstName,2.1,2.2,2.3,...,14.5,14.6,14.7,15.1,15.2,15.3,15.4,15.5,15.6,15.7
0,0,arush.godha@berkeley.edu,1.0,1.0,arush.godha@berkeley.edu,Godha,Arush,7.0,7.0,7.0,...,Highly skilled at prototyping,Highly skilled at team management and prototyping,No Response,Be better at prototyping,No comments,No comments,No comments,No comments,No comments,No Response
1,1,aaronlee5702@berkeley.edu,1.0,2.0,aaronlee5702@berkeley.edu,Lee,Aaron,6.0,6.0,6.0,...,design and manufacturing,drawings,No Response,more design work,more drawings and brain stormingq,more design work,more work,more sleep,more manufacturing,No Response
2,2,naomi_nogueira@berkeley.edu,1.0,3.0,naomi_nogueira@berkeley.edu,Nogueira,Naomi,6.0,6.0,6.0,...,Helped assemble the prototype and came up with...,Makes sure the team in on track and helped wit...,No Response,More communication,No Response,have more confidence in their ideas,Could speak up more,No Response,No Response,No Response
3,3,knyi@berkeley.edu,1.0,4.0,knyi@berkeley.edu,Nyi,Khant,7.0,6.0,5.0,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response
4,4,bramos6837@berkeley.edu,1.0,5.0,bramos6837@berkeley.edu,Ramos-Bailon,Brandon Isaiah,6.0,6.0,6.0,...,Dedicated many hours to printing the box.,Led much of presentation approach and philosop...,No Response,Help more with the manufacturing and take lead...,Name files better and send them with the part ...,Feel confident to push ideas and disagree with...,Even if it is not a lot ask where you can help...,Communicate better and distribute work.,Better communicate meeting times and deadlines.,No Response
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,167,pbrunet@berkeley.edu,30.0,2.0,pbrunet@berkeley.edu,Brunet,Pablo,7.0,7.0,7.0,...,in charge of coordinating manufacturing,came up with final design,No Response,did well,did well,did well,did well,did well,did well,No Response
168,168,garciaeilyn@berkeley.edu,30.0,3.0,garciaeilyn@berkeley.edu,Garcia,Eilyn,7.0,7.0,7.0,...,great at contributing to the group,great at contributing to the group,No Response,more communication,more communication,more communication,more communication,more communication,more communication,No Response
169,169,tifkurnia2004@berkeley.edu,30.0,4.0,tifkurnia2004@berkeley.edu,Kurniawan,Tiffelyn,7.0,7.0,7.0,...,Keep track of everything,Designing,No Response,None,None,None,None,None,None,No Response
170,170,elind1@berkeley.edu,30.0,5.0,elind1@berkeley.edu,Lind,Eric,6.0,5.0,6.0,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response
171,171,wongton@berkeley.edu,30.0,6.0,wongton@berkeley.edu,Wong,Brandon,6.0,6.0,6.0,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response

In [21]:
quant = [str(x) for x in list(dictionary[dictionary["type"] == 'quantitative']["question_id"])]

numerical_data = full_cleaned_data[['TeamNumber', 'TeammateNumber','2.1',
 '2.2',
 '2.3',
 '4.1',
 '4.2',
 '4.3',
 '4.4', 
 '4.5',
 '4.6',
 '4.7',
 '5.1',
 '5.2',
 '5.3',
 '5.4', 
 '5.5',
 '5.6',
 '5.7',
 '16.1', '16.2', '16.3', '16.4', '16.5', '16.6', '16.7',
'17.1', '17.2', '17.3', '17.4', '17.5', '17.6', '17.7',
'18.1', '18.2', '18.3', '18.4', '18.5', '18.6', '18.7',
'19.1', '19.2', '19.3', '19.4', '19.5', '19.6', '19.7',]]
numerical_data = numerical_data.replace({"No Response" : np.nan})
numerical_data.head()

,TeamNumber,TeammateNumber,2.1,2.2,2.3,4.1,4.2,4.3,4.4,4.5,...,18.5,18.6,18.7,19.1,19.2,19.3,19.4,19.5,19.6,19.7
0,1.0,1.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,7.0,NaN,7.0,7.0,7.0,7.0,7.0,7.0,NaN
1,1.0,2.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,NaN,6.0,6.0,6.0,6.0,6.0,6.0,NaN
2,1.0,3.0,6.0,6.0,6.0,6.0,6.0,6.0,7.0,7.0,...,7.0,7.0,NaN,6.0,7.0,7.0,7.0,7.0,7.0,NaN
3,1.0,4.0,7.0,6.0,5.0,5.0,5.0,4.0,5.0,5.0,...,6.0,5.0,NaN,5.0,5.0,5.0,5.0,5.0,5.0,NaN
4,1.0,5.0,6.0,6.0,6.0,7.0,7.0,7.0,7.0,7.0,...,7.0,7.0,NaN,7.0,6.0,7.0,7.0,7.0,7.0,NaN

In [22]:
numerical_data = numerical_data.astype(float)
numerical_data["Email"] = full_cleaned_data["Email"]
numerical_data = numerical_data.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index()
full_cleaned_data = full_cleaned_data.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index()
roster = roster.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index()

In [23]:
numerical_data

,index,TeamNumber,TeammateNumber,2.1,2.2,2.3,4.1,4.2,4.3,4.4,...,18.6,18.7,19.1,19.2,19.3,19.4,19.5,19.6,19.7,Email
0,0,1.0,1.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,NaN,7.0,7.0,7.0,7.0,7.0,7.0,NaN,arush.godha@berkeley.edu
1,1,1.0,2.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,NaN,6.0,6.0,6.0,6.0,6.0,6.0,NaN,aaronlee5702@berkeley.edu
2,2,1.0,3.0,6.0,6.0,6.0,6.0,6.0,6.0,7.0,...,7.0,NaN,6.0,7.0,7.0,7.0,7.0,7.0,NaN,naomi_nogueira@berkeley.edu
3,3,1.0,4.0,7.0,6.0,5.0,5.0,5.0,4.0,5.0,...,5.0,NaN,5.0,5.0,5.0,5.0,5.0,5.0,NaN,knyi@berkeley.edu
4,4,1.0,5.0,6.0,6.0,6.0,7.0,7.0,7.0,7.0,...,7.0,NaN,7.0,6.0,7.0,7.0,7.0,7.0,NaN,bramos6837@berkeley.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,167,30.0,2.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,NaN,7.0,7.0,7.0,7.0,7.0,7.0,NaN,pbrunet@berkeley.edu
168,168,30.0,3.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,NaN,7.0,7.0,7.0,7.0,7.0,7.0,NaN,garciaeilyn@berkeley.edu
169,169,30.0,4.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,NaN,7.0,7.0,7.0,7.0,7.0,7.0,NaN,tifkurnia2004@berkeley.edu
170,170,30.0,5.0,6.0,5.0,6.0,6.0,6.0,6.0,7.0,...,6.0,NaN,7.0,7.0,7.0,7.0,7.0,7.0,NaN,elind1@berkeley.edu
171,171,30.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,NaN,6.0,6.0,6.0,6.0,6.0,6.0,NaN,wongton@berkeley.edu

In [24]:
#Functions 

def calculate_team_averages(df):
    # Creates a DataFrame with the averages per team for each question
    return df.groupby("TeamNumber").agg(np.nanmean)[numerical_questions]

def get_team_data(team_number):
    # Returns new dataframe containing only TEAM_NUMBER's data
    return numerical_data[numerical_data['TeamNumber'] == team_number]

def get_team_average(team_number, question):
    # Gets TEAM_NUMBER's average on the specified question
    temp_df = get_team_data(team_number)
    return np.nanmean(temp_df[question])

def get_team_std(team_number, teammate_number, question):
    # Gets TEAM_NUMBER's standard deviation on the specified question and should not include self
    temp_df = get_team_data(team_number)
    temp_df = temp_df[temp_df['TeammateNumber'] != teammate_number]
    
    return np.nanstd(temp_df[question])

def get_teammates_average(team_number, teammate_number, question):
    # Gets TEAM_NUMBER's average on the specified question
    # omits data from current student given by TEAMMATE_NUMBER 
    temp_df = get_team_data(team_number)
    
    temp_df = temp_df[temp_df['TeammateNumber'] != teammate_number]
    
    return np.nanmean(temp_df[question])


def get_student_answer(team_number, teammate_number, question):
    # Returns the current student's response for the specified question
    temp_df = get_team_data(team_number)
    
    temp_df = temp_df[temp_df['TeammateNumber'] == teammate_number]
    
    return float(temp_df[question])
    #return temp_df[question]

def get_class_average(question):
    # Returns the class average for QUESTION
    return np.mean(numerical_data[question])

def get_class_stdv(question):
    # Returns the class std dev for QUESTION
    return np.std(numerical_data[question])

## Part 1: Identification Information

In [25]:
#roster = roster.rename({"FullName": "Full Name"}, axis=1)

In [26]:
#roster["Email"] = roster["Email Address"]

In [27]:
roster["FullName"] = roster["FirstName"] + ' ' + roster["LastName"]

In [28]:
analysis_v2 = roster[["FullName", "Email", "TeamNumber", "TeammateNumber"]]

In [29]:
analysis_v2 = analysis_v2.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index(drop=True)

In [30]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber
0,Arush Godha,arush.godha@berkeley.edu,1,1
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3
3,Khant Nyi,knyi@berkeley.edu,1,4
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5
...,...,...,...,...
167,Pablo Brunet,pbrunet@berkeley.edu,30,2
168,Eilyn Garcia,garciaeilyn@berkeley.edu,30,3
169,Tiffelyn Kurniawan,tifkurnia2004@berkeley.edu,30,4
170,Eric Lind,elind1@berkeley.edu,30,5
171,Brandon Wong,wongton@berkeley.edu,30,6

## Part 2: Skills Assessment

In [31]:
...

Ellipsis

## Part 3: Survey Questionnairre

In [32]:
question_shorthand = {}
question_shorthand[2.1] = ['SharedGoalTeamAvg', 'SharedGoalClassAvg', 'SharedGoalClassStDev']
question_shorthand[2.2] = ['IndvGoalTeamAvg', 'IndvGoalClassAvg', 'IndvGoalClassStDev']
question_shorthand[2.3] = ['SupportTeamAvg', 'SupportClassAvg', 'SupportClassStDev']
question_shorthand[3.0] = ['Goal1', 'Goal2', 'Goal3', 'Goal4', 'Goal5', 'Goal6', 'Goal7']
question_shorthand[3.5] = ['NewGoal1', 'NewGoal2', 'NewGoal3', 'NewGoal4', 'NewGoal5', 'NewGoal6', 'NewGoal7']
question_shorthand[4.1] = ['CommunicateTeamAvg', 'CommunicateClassAvg', 'CommunicateClassStDev']
question_shorthand[4.2] = ['WorkAllocTeamAvg', 'WorkAllocClassAvg', 'WorkAllocClassStDev']
question_shorthand[4.3] = ['RoleTeamAvg', 'RoleClassAvg', 'RoleClassStDev']
question_shorthand[4.4] = ['EnjoyTeamAvg', 'EnjoyClassAvg', 'EnjoyClassStDev']
question_shorthand[4.5] = ['ConflictResTeamAvg', 'ConflictResClassAvg', 'ConflictResClassStDev']
question_shorthand[4.6] = ['EfficiencyTeamAvg', 'EfficiencyClassAvg', 'EfficiencyClassStDev']
question_shorthand[4.7] = ['ExpressionTeamAvg', 'ExpressionClassAvg', 'ExpressionClassStDev']

question_shorthand[5.0] = ['MyPoints', 'TeammateAvgPoints', 'ExpectedPoints', 'Percent', 'AveragePointsAllocated', 'StDevPointsAllocated']
question_shorthand[5.1] = 'Work Contribution Teammate 1'
question_shorthand[5.2] = 'Work Contribution Teammate 2'
question_shorthand[5.3] = 'Work Contribution Teammate 3'
question_shorthand[5.4] = 'Work Contribution Teammate 4'
question_shorthand[5.5] = 'Work Contribution Teammate 5'
question_shorthand[5.6] = 'Work Contribution Teammate 6'
question_shorthand[5.6] = 'Work Contribution Teammate 7'#might need to increase this based on team size
question_shorthand[6.0] = ['DidWellMe','DidWell1','DidWell2','DidWell3','DidWell4', 'DidWell5','DidWell6','DidWell7']
question_shorthand[6.5] = ['GPTDidWellMe','GPTDidWell1','GPTDidWell2','GPTDidWell3','GPTDidWell4', 'GPTDidWell5','GPTDidWell6','GPTDidWell7']
question_shorthand[7] = ['DoDiffMe', 'DoDiff1', 'DoDiff2', 'DoDiff3', 'DoDiff4','DoDiff5', 'DoDiff6', 'DoDiff7']
question_shorthand[7.5] = ['GPTDoDiffMe', 'GPTDoDiff1', 'GPTDoDiff2', 'GPTDoDiff3', 'GPTDoDiff4','GPTDoDiff5', 'GPTDoDiff6', 'GPTDoDiff7']
#question_shorthand[9.1] = 'ImproveAmt1'
#question_shorthand[9.2] = 'ImproveAmt2'
#question_shorthand[9.3] = 'ImproveAmt3'
#question_shorthand[10.1] = ["AskFeedbackClassAvg", "AskFeedbackClassStDev"]
#question_shorthand[10.2] = ["AskHelpClassAvg", "AskHelpClassStDev"]
#question_shorthand[10.3] = ["ValueContrClassAvg", "ValueContrClassStdev"]
#question_shorthand[10.4] = ["ReflectClassAvg", "ReflectClassStDev"]
#questions 11-13 are just imported as questions themselves as columns
question_shorthand[14] = ["ContributeMe", "Contribute1", "Contribute2", "Contribute3", "Contribute4", "Contribute5", "Contribute6", "Contribute7"]
question_shorthand[15] = ['ImproveMe', 'Improve1', 'Improve2', 'Improve3', 'Improve4', 'Improve5', 'Improve6', 'Improve7']
#question_shorthand[24] = ["GPTContributeMe", "GPTContribute1", "GPTContribute2", "GPTContribute3", "GPTContribute4", "GPTContribute5", "GPTContribute6", "GPTContribute7"]
#question_shorthand[25] = ['GPTImproveMe', 'GPTImprove1', 'GPTImprove2', 'GPTImprove3', 'GPTImprove4', 'GPTImprove5', 'GPTImprove6', 'GPTImprove7']
question_shorthand[16] = ['InitiativeMe', 'InitiativeTeammateAvg', 'InitiativeClassAvg', 'InitiativeClassStDev']
question_shorthand[17] = ['CommunicateMe', 'CommunicateTeammateAvg', 'Communicate2ClassAvg', 'Communicate2ClassStDev']
question_shorthand[18] = ['ExpertiseMe', 'ExpertiseTeammateAvg', 'ExpertiseClassAvg', 'ExpertiseClassStDev']
question_shorthand[19] = ['RespectMe', 'RespectTeammateAvg', 'RespectClassAvg', 'RespectClassStDev']
#question_shorthand[38.1] = 'ImproveAmt1'
#question_shorthand[38.2] = 'ImproveAmt2'
#question_shorthand[38.3] = 'ImproveAmt3'

### 2.1

In [33]:
#Question 2.1

question_2_1 = dictionary[dictionary["question_id"] == 2.1].reset_index()["question"][0]
analysis_v2[question_2_1] = numerical_data["2.1"]

In [34]:
#Question 2.1 team average
question_2_1_0 = question_shorthand[2.1][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "2.1"), 1))

analysis_v2[question_2_1_0] = lst_responses

In [35]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg
0,Arush Godha,arush.godha@berkeley.edu,1,1,7.0,6.5
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2,6.0,6.5
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3,6.0,6.5
3,Khant Nyi,knyi@berkeley.edu,1,4,7.0,6.5
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5,6.0,6.5
...,...,...,...,...,...,...
167,Pablo Brunet,pbrunet@berkeley.edu,30,2,7.0,6.6
168,Eilyn Garcia,garciaeilyn@berkeley.edu,30,3,7.0,6.6
169,Tiffelyn Kurniawan,tifkurnia2004@berkeley.edu,30,4,7.0,6.6
170,Eric Lind,elind1@berkeley.edu,30,5,6.0,6.6
171,Brandon Wong,wongton@berkeley.edu,30,6,6.0,6.6

In [36]:
#Question 2.1 class avg
question_2_1_1 = question_shorthand[2.1][1]

analysis_v2[question_2_1_1] = round(get_class_average("2.1"), 1)

In [23]:


#Question 2.1 class std
question_2_1_2 = question_shorthand[2.1][2]

analysis_v2[question_2_1_2] = round(get_class_stdv("2.1"), 1)

In [24]:
#analysis_v2.iloc[97]

### 2.2

In [25]:
#Question 2.2

question_2_2 = dictionary[dictionary["question_id"] == 2.2].reset_index()["question"][0]
analysis_v2[question_2_2] = numerical_data["2.2"]

In [26]:
#Question 2.2 team average
question_2_2_0 = question_shorthand[2.2][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "2.2"), 1))

analysis_v2[question_2_2_0] = lst_responses

In [27]:
#Question 2.2 class avg
question_2_2_1 = question_shorthand[2.2][1]

analysis_v2[question_2_2_1] = round(get_class_average("2.2"), 1)

In [28]:
#Question 2.2 class std
question_2_2_2 = question_shorthand[2.2][2]

analysis_v2[question_2_2_2] = round(get_class_stdv("2.2"), 1)

In [29]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,IndvGoalClassAvg,IndvGoalClassStDev
0,Arush Godha,arush.godha@berkeley.edu,1,1,7.0,6.8,6.1,1.1,7.0,6.2,6.0,1.1
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2,NaN,6.8,6.1,1.1,NaN,6.2,6.0,1.1
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3,6.0,6.8,6.1,1.1,5.0,6.2,6.0,1.1
3,Khant Nyi,knyi@berkeley.edu,1,4,7.0,6.8,6.1,1.1,6.0,6.2,6.0,1.1
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5,NaN,6.8,6.1,1.1,NaN,6.2,6.0,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...
167,Pablo Brunet,pbrunet@berkeley.edu,30,2,7.0,6.6,6.1,1.1,7.0,6.6,6.0,1.1
168,Eilyn Garcia,garciaeilyn@berkeley.edu,30,3,7.0,6.6,6.1,1.1,7.0,6.6,6.0,1.1
169,Tiffelyn Kurniawan,tifkurnia2004@berkeley.edu,30,4,7.0,6.6,6.1,1.1,7.0,6.6,6.0,1.1
170,Eric Lind,elind1@berkeley.edu,30,5,NaN,6.6,6.1,1.1,NaN,6.6,6.0,1.1
171,Brandon Wong,wongton@berkeley.edu,30,6,5.0,6.6,6.1,1.1,5.0,6.6,6.0,1.1

### 2.3

In [30]:
#Question 2.3

question_2_3 = dictionary[dictionary["question_id"] == 2.3].reset_index()["question"][0]
analysis_v2[question_2_3] = numerical_data["2.3"]

In [31]:
#Question 2.3 team average
question_2_3_0 = question_shorthand[2.3][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "2.3"), 1))

analysis_v2[question_2_3_0] = lst_responses

In [32]:
#Question 2.3 class avg
question_2_3_1 = question_shorthand[2.3][1]

analysis_v2[question_2_3_1] = round(get_class_average("2.3"), 1)

In [33]:
#Question 2.3 class std
question_2_3_2 = question_shorthand[2.3][2]

analysis_v2[question_2_3_2] = round(get_class_stdv("2.3"), 1)

### 3

In [34]:
question_3 = dictionary[dictionary["question_id"] == 3.0].reset_index()["question"][0]

In [35]:
analysis_v2[question_3] = full_cleaned_data["3"]

In [36]:
#goal 1
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 1].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_1 = question_shorthand[3.0][0]
analysis_v2[question_3_1] = lst_responses

In [37]:
#goal 2
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 2].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_2 = question_shorthand[3.0][1]
analysis_v2[question_3_2] = lst_responses

In [38]:
#goal 3
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 3].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_3 = question_shorthand[3.0][2]
analysis_v2[question_3_3] = lst_responses

In [39]:
#goal 4
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 4].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_4 = question_shorthand[3.0][3]
analysis_v2[question_3_4] = lst_responses

In [40]:
#goal 5
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 5].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_5 = question_shorthand[3.0][4]
analysis_v2[question_3_5] = lst_responses

In [41]:

#goal 6
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 6].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_6 = question_shorthand[3.0][5]
analysis_v2[question_3_6] = lst_responses

In [42]:
#goal 7
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 7].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_7 = question_shorthand[3.0][6]
analysis_v2[question_3_7] = lst_responses

In [43]:
#no adjusted goals

### 4.1

In [44]:
#Question 4.1

question_4_1 = dictionary[dictionary["question_id"] == 4.1].reset_index()["question"][0]
analysis_v2[question_4_1] = numerical_data["4.1"]

In [45]:
#analysis_v2

In [46]:
#Question 4.1 team average
question_4_1_0 = question_shorthand[4.1][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.1"), 1))

analysis_v2[question_4_1_0] = lst_responses

In [47]:
#analysis_v2

In [48]:
#Question 4.1 class avg
question_4_1_1 = question_shorthand[4.1][1]

analysis_v2[question_4_1_1] = round(get_class_average("4.1"), 1)

In [49]:
#Question 4.1 class std
question_4_1_2 = question_shorthand[4.1][2]

analysis_v2[question_4_1_2] = round(get_class_stdv("4.1"), 1)

### 4.2

In [50]:
#Question 4.2

question_4_2 = dictionary[dictionary["question_id"] == 4.2].reset_index()["question"][0]
analysis_v2[question_4_2] = numerical_data["4.2"]

In [51]:
#Question 4.2 team average
question_4_2_0 = question_shorthand[4.2][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.2"), 1))

analysis_v2[question_4_2_0] = lst_responses

In [52]:
#Question 4.2 class avg
question_4_2_1 = question_shorthand[4.2][1]

analysis_v2[question_4_2_1] = round(get_class_average("4.2"), 1)

In [53]:
#Question 4.2 class std
question_4_2_2 = question_shorthand[4.2][2]

analysis_v2[question_4_2_2] = round(get_class_stdv("4.2"), 1)

### 4.3

In [54]:
#Question 4.3

question_4_3 = dictionary[dictionary["question_id"] == 4.3].reset_index()["question"][0]
analysis_v2[question_4_3] = numerical_data["4.3"]

In [55]:
#Question 4.1 team average
question_4_3_0 = question_shorthand[4.3][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.3"), 1))

analysis_v2[question_4_3_0] = lst_responses

In [56]:
#Question 4.3 class avg
question_4_3_1 = question_shorthand[4.3][1]

analysis_v2[question_4_3_1] = round(get_class_average("4.3"), 1)

In [57]:
#Question 4.3 class std
question_4_3_2 = question_shorthand[4.3][2]

analysis_v2[question_4_3_2] = round(get_class_stdv("4.3"), 1)

### 4.4

In [58]:
#Question 4.4

question_4_4 = dictionary[dictionary["question_id"] == 4.4].reset_index()["question"][0]
analysis_v2[question_4_4] = numerical_data["4.4"]

In [59]:
#Question 4.4 team average
question_4_4_0 = question_shorthand[4.4][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.4"), 1))

analysis_v2[question_4_4_0] = lst_responses

In [60]:
#Question 4.4 class avg
question_4_4_1 = question_shorthand[4.4][1]

analysis_v2[question_4_4_1] = round(get_class_average("4.4"), 1)

In [61]:
#Question 4.4 class std
question_4_4_2 = question_shorthand[4.4][2]

analysis_v2[question_4_4_2] = round(get_class_stdv("4.4"), 1)

### 4.5

In [62]:
#Question 4.5

question_4_5 = dictionary[dictionary["question_id"] == 4.5].reset_index()["question"][0]
analysis_v2[question_4_5] = numerical_data["4.5"]

In [63]:
#Question 4.5 team average
question_4_5_0 = question_shorthand[4.5][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.5"), 1))

analysis_v2[question_4_5_0] = lst_responses

In [64]:
#Question 4.5 class avg
question_4_5_1 = question_shorthand[4.5][1]

analysis_v2[question_4_5_1] = round(get_class_average("4.5"), 1)

In [65]:
#Question 4.5 class std
question_4_5_2 = question_shorthand[4.5][2]

analysis_v2[question_4_5_2] = round(get_class_stdv("4.5"), 1)

### 4.6

In [66]:
#Question 4.6

question_4_6 = dictionary[dictionary["question_id"] == 4.6].reset_index()["question"][0]
analysis_v2[question_4_6] = numerical_data["4.6"]

#Question 4.6 team average
question_4_6_0 = question_shorthand[4.6][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.6"), 1))

analysis_v2[question_4_6_0] = lst_responses

#Question 4.6 class avg
question_4_6_1 = question_shorthand[4.6][1]

analysis_v2[question_4_6_1] = round(get_class_average("4.6"), 1)

#Question 4.6 class std
question_4_6_2 = question_shorthand[4.6][2]

analysis_v2[question_4_6_2] = round(get_class_stdv("4.6"), 1)

### 4.7

In [67]:
#Question 4.7

question_4_7 = dictionary[dictionary["question_id"] == 4.7].reset_index()["question"][0]
analysis_v2[question_4_7] = numerical_data["4.7"]

#Question 4.7 team average
question_4_7_0 = question_shorthand[4.7][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.7"), 1))

analysis_v2[question_4_7_0] = lst_responses

#Question 4.7 class avg
question_4_7_1 = question_shorthand[4.7][1]

analysis_v2[question_4_7_1] = round(get_class_average("4.7"), 1)

#Question 4.7 class std
question_4_7_2 = question_shorthand[4.7][2]

analysis_v2[question_4_7_2] = round(get_class_stdv("4.7"), 1)

### 5

In [68]:
#Question 5.1-5.6. will need to change this according to how many people are on a team
question_5_1 = dictionary[dictionary["question_id"] == 5.1].reset_index()["question"][0]
question_5_2 = dictionary[dictionary["question_id"] == 5.2].reset_index()["question"][0]
question_5_3 = dictionary[dictionary["question_id"] == 5.3].reset_index()["question"][0]
question_5_4 = dictionary[dictionary["question_id"] == 5.4].reset_index()["question"][0]
question_5_5 = dictionary[dictionary["question_id"] == 5.5].reset_index()["question"][0]
question_5_6 = dictionary[dictionary["question_id"] == 5.6].reset_index()["question"][0]
question_5_7 = dictionary[dictionary["question_id"] == 5.7].reset_index()["question"][0]

analysis_v2[question_5_1] = full_cleaned_data[["5.1"]]
analysis_v2[question_5_2] = full_cleaned_data[["5.2"]]
analysis_v2[question_5_3] = full_cleaned_data[["5.3"]]
analysis_v2[question_5_4] = full_cleaned_data[["5.4"]]
analysis_v2[question_5_5] = full_cleaned_data[["5.5"]]
analysis_v2[question_5_6] = full_cleaned_data[["5.6"]]
analysis_v2[question_5_7] = full_cleaned_data[["5.7"]]

In [69]:
#Calculations

#MyPoints
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    student_df = team_df[team_df["TeammateNumber"] == student_teammate_number].reset_index()
    question_needed = '5.' + str(int(student_teammate_number))
    #print(student_df)
    lst_responses.append(student_df[question_needed].reset_index()[question_needed][0])
    
question_5_a = question_shorthand[5][0]
analysis_v2[question_5_a] = lst_responses

In [70]:
#TeammateAvgPoints
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    question_needed = '5.' + str(int(student_teammate_number))
    lst_responses.append(round(get_teammates_average(student_team_number, student_teammate_number, question_needed), 1))

question_5_b = question_shorthand[5][1]
analysis_v2[question_5_b] = lst_responses

In [71]:
#ExpectedPoints
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    lst_responses.append(round(100/team_size, 1))

question_5_c = question_shorthand[5][2]
analysis_v2[question_5_c] = lst_responses

In [72]:
#Percent
question_5_d = question_shorthand[5][3]
analysis_v2[question_5_d] = round((analysis_v2[question_5_b] / analysis_v2[question_5_c]) * 100, 1)

In [73]:
#AveragePointsAllocated
lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    
    temp_q5_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number][["5.1", "5.2", "5.3", "5.4", "5.5", "5.6"]]
    temp_q5_df = temp_q5_df.replace({"No Response" : np.nan}).astype(float)
    sum_points = sum(temp_q5_df.reset_index().drop("index", axis=1).iloc[int(student_teammate_number) - 1])
    lst_responses.append(round(sum_points/team_size, 1))

question_5_e = question_shorthand[5][4]
analysis_v2[question_5_e] = lst_responses

In [74]:
#StDevPointsAllocated
lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    
    temp_q5_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number][["5.1", "5.2", "5.3", "5.4", "5.5", "5.6"]]
    temp_q5_df = temp_q5_df.replace({"No Response" : np.nan}).astype(float)
    arr = temp_q5_df.reset_index().drop("index", axis=1).dropna().to_numpy().flatten()
    std = np.std(arr[arr != 0])
    lst_responses.append(round(std, 1))

question_5_f = question_shorthand[5][5]
analysis_v2[question_5_f] = lst_responses

In [75]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 4,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 5,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 6,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 7,MyPoints,TeammateAvgPoints,ExpectedPoints,Percent,AveragePointsAllocated,StDevPointsAllocated
0,Arush Godha,arush.godha@berkeley.edu,1,1,7.0,6.8,6.1,1.1,7.0,6.2,...,16,18,16,0,16,9.3,16.7,55.7,16.7,4.8
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2,NaN,6.8,6.1,1.1,NaN,6.2,...,No Response,No Response,No Response,No Response,No Response,20.5,16.7,122.8,NaN,4.8
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3,6.0,6.8,6.1,1.1,5.0,6.2,...,10,30,13,0,15,17.0,16.7,101.8,16.7,4.8
3,Khant Nyi,knyi@berkeley.edu,1,4,7.0,6.8,6.1,1.1,6.0,6.2,...,15,18,16,0,15,14.3,16.7,85.6,16.7,4.8
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5,NaN,6.8,6.1,1.1,NaN,6.2,...,No Response,No Response,No Response,No Response,No Response,21.5,16.7,128.7,NaN,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Pablo Brunet,pbrunet@berkeley.edu,30,2,7.0,6.6,6.1,1.1,7.0,6.6,...,16,16,17,0,17,20.8,16.7,124.6,16.7,10.3
168,Eilyn Garcia,garciaeilyn@berkeley.edu,30,3,7.0,6.6,6.1,1.1,7.0,6.6,...,0,0,0,0,0,15.2,16.7,91.0,16.7,10.3
169,Tiffelyn Kurniawan,tifkurnia2004@berkeley.edu,30,4,7.0,6.6,6.1,1.1,7.0,6.6,...,16,16,18,1,16,10.2,16.7,61.1,16.5,10.3
170,Eric Lind,elind1@berkeley.edu,30,5,NaN,6.6,6.1,1.1,NaN,6.6,...,No Response,No Response,No Response,No Response,No Response,13.4,16.7,80.2,NaN,10.3
171,Brandon Wong,wongton@berkeley.edu,30,6,5.0,6.6,6.1,1.1,5.0,6.6,...,14,14,15,14,15,14.0,16.7,83.8,14.3,10.3

### 6

In [76]:
#Didwellme 

lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    temp_q6_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    response = temp_q6_df[temp_q6_df["TeammateNumber"] == student_teammate_number].reset_index()["6"][0]
    lst_responses.append(response)

question_6_a = question_shorthand[6][0]
analysis_v2[question_6_a] = lst_responses

In [77]:
#DidWell1 thru DidWell6

subset_df = analysis_v2[["TeamNumber", "TeammateNumber", "DidWellMe"]]
#subset_df[subset_df["TeammateNumber"] == 1]
#subset_df

lst_responses_1 = []
lst_responses_2 = []
lst_responses_3 = []
lst_responses_4 = []
lst_responses_5 = []
lst_responses_6 = []
lst_responses_7 = []


for team in subset_df["TeamNumber"]:#.unique():
    team_series = subset_df[subset_df["TeamNumber"] == team].reset_index()["DidWellMe"]
    if len(team_series) == 1:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(np.nan)
        lst_responses_3.append(np.nan)
        lst_responses_4.append(np.nan)
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 2:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(np.nan)
        lst_responses_4.append(np.nan)
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 3:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(np.nan)
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 4:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 5:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(team_series[4])
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 6:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(team_series[4])
        lst_responses_6.append(team_series[5])
        lst_responses_7.append(np.nan)
    if len(team_series) == 7:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(team_series[4])
        lst_responses_6.append(team_series[5])
        lst_responses_7.append(team_series[6])

question_6_b = question_shorthand[6][1]
question_6_c = question_shorthand[6][2]
question_6_d = question_shorthand[6][3]
question_6_e = question_shorthand[6][4]
question_6_f = question_shorthand[6][5]
question_6_g = question_shorthand[6][6]
question_6_h = question_shorthand[6][7]
analysis_v2[question_6_b] = lst_responses_1
analysis_v2[question_6_c] = lst_responses_2
analysis_v2[question_6_d] = lst_responses_3
analysis_v2[question_6_e] = lst_responses_4
analysis_v2[question_6_f] = lst_responses_5
analysis_v2[question_6_g] = lst_responses_6
analysis_v2[question_6_h] = lst_responses_7

### 7

In [78]:
#DoDiffMe
lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    temp_q7_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    #temp_q7_df = temp_q7_df.replace({"No Response" : np.nan}).astype(float)
    response = temp_q7_df[temp_q7_df["TeammateNumber"] == student_teammate_number].reset_index()["7"][0]
    lst_responses.append(response)

question_7_a = question_shorthand[7][0]
analysis_v2[question_7_a] = lst_responses

In [79]:
#DoDiff1 thru DoDiff6

subset_df = analysis_v2[["TeamNumber", "TeammateNumber", "DoDiffMe"]]
#subset_df[subset_df["TeammateNumber"] == 1]
#subset_df

lst_responses_1 = []
lst_responses_2 = []
lst_responses_3 = []
lst_responses_4 = []
lst_responses_5 = []
lst_responses_6 = []
lst_responses_7 = []

for team in subset_df["TeamNumber"]:#.unique():
    team_series = subset_df[subset_df["TeamNumber"] == team].reset_index()["DoDiffMe"]
    if len(team_series) == 1:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(np.nan)
        lst_responses_3.append(np.nan)
        lst_responses_4.append(np.nan)
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 2:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(np.nan)
        lst_responses_4.append(np.nan)
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 3:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(np.nan)
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 4:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(np.nan)
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 5:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(team_series[4])
        lst_responses_6.append(np.nan)
        lst_responses_7.append(np.nan)
    if len(team_series) == 6:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(team_series[4])
        lst_responses_6.append(team_series[5])
        lst_responses_7.append(np.nan)
    if len(team_series) == 7:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        lst_responses_5.append(team_series[4])
        lst_responses_6.append(team_series[5])
        lst_responses_7.append(team_series[6])
        
question_7_b = question_shorthand[7][1]
question_7_c = question_shorthand[7][2]
question_7_d = question_shorthand[7][3]
question_7_e = question_shorthand[7][4]
question_7_f = question_shorthand[7][5]
question_7_g = question_shorthand[7][6]
question_7_h = question_shorthand[7][7]
analysis_v2[question_7_b] = lst_responses_1
analysis_v2[question_7_c] = lst_responses_2
analysis_v2[question_7_d] = lst_responses_3
analysis_v2[question_7_e] = lst_responses_4
analysis_v2[question_7_f] = lst_responses_5
analysis_v2[question_7_g] = lst_responses_6
analysis_v2[question_7_h] = lst_responses_7

### 9

In [80]:
#analysis_v2[question_shorthand[9.1]] = full_cleaned_data["9.1"]
#analysis_v2[question_shorthand[9.2]] = full_cleaned_data["9.2"]
#analysis_v2[question_shorthand[9.3]] = full_cleaned_data["9.3"]

### 10 (not used here but can use functions below)

In [81]:
#analysis_v2[question_shorthand[10.1][0]] = get_class_average("10.1")
#analysis_v2[question_shorthand[10.1][1]] = get_class_stdv("10.1")

#analysis_v2[question_shorthand[10.2][0]] = get_class_average("10.2")
#analysis_v2[question_shorthand[10.2][1]] = get_class_stdv("10.2")

#analysis_v2[question_shorthand[10.3][0]] = get_class_average("10.3")
#analysis_v2[question_shorthand[10.3][1]] = get_class_stdv("10.3")

### 11

In [82]:
#question_11 = dictionary[dictionary["question_id"] == 11].reset_index()["question"][0]
#analysis_v2[question_11] = full_cleaned_data["11"]

### 12

In [119]:
#question_12 = dictionary[dictionary["question_id"] == 12].reset_index()["question"][0]
#analysis_v2[question_12] = full_cleaned_data["12"]

### 14

In [83]:
#14.1 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '14.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_14_me = question_shorthand[14][0]
analysis_v2[question_14_me] = lst_responses

In [84]:
analysis_v2.head()

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,DidWell7,DoDiffMe,DoDiff1,DoDiff2,DoDiff3,DoDiff4,DoDiff5,DoDiff6,DoDiff7,ContributeMe
0,Arush Godha,arush.godha@berkeley.edu,1,1,7.0,6.8,6.1,1.1,7.0,6.2,...,NaN,Maybe communication.,Maybe communication.,No Response,I feel like we could do a better job of splitt...,"we are doing pretty well, but it would be bett...",No Response,I would like us to set better deadlines.,NaN,Working well towards ideation
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2,NaN,6.8,6.1,1.1,NaN,6.2,...,NaN,No Response,Maybe communication.,No Response,I feel like we could do a better job of splitt...,"we are doing pretty well, but it would be bett...",No Response,I would like us to set better deadlines.,NaN,No Response
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3,6.0,6.8,6.1,1.1,5.0,6.2,...,NaN,I feel like we could do a better job of splitt...,Maybe communication.,No Response,I feel like we could do a better job of splitt...,"we are doing pretty well, but it would be bett...",No Response,I would like us to set better deadlines.,NaN,Helped with a lot of aspects and delvelopment ...
3,Khant Nyi,knyi@berkeley.edu,1,4,7.0,6.8,6.1,1.1,6.0,6.2,...,NaN,"we are doing pretty well, but it would be bett...",Maybe communication.,No Response,I feel like we could do a better job of splitt...,"we are doing pretty well, but it would be bett...",No Response,I would like us to set better deadlines.,NaN,No Response
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5,NaN,6.8,6.1,1.1,NaN,6.2,...,NaN,No Response,Maybe communication.,No Response,I feel like we could do a better job of splitt...,"we are doing pretty well, but it would be bett...",No Response,I would like us to set better deadlines.,NaN,No Response

In [85]:
#14

question_14_1 = question_shorthand[14][1]
question_14_2 = question_shorthand[14][2]
question_14_3 = question_shorthand[14][3]
question_14_4 = question_shorthand[14][4]
question_14_5 = question_shorthand[14][5]
question_14_6 = question_shorthand[14][6]
question_14_7 = question_shorthand[14][7]

feedback_1 = []
feedback_2 = []
feedback_3 = []
feedback_4 = []
feedback_5 = [] 
feedback_6 = []
feedback_7 = []#need to adjust to max team size

#possibilities = ["14.1", "14.2", "14.3", "14.4", "14.5", "14.6"]
for i in range(len(full_cleaned_data)):
    my_teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    my_team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_number_str = str(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == my_team_number]
    list_feedback_for_me = list(my_team_df["14." + str(my_teammate_number)])
    num_teammates = len(list_feedback_for_me)
    extra_needed = 7 - num_teammates
    placeholders = [''] * extra_needed
    all_feedback = list_feedback_for_me + placeholders

    feedback_1.append(all_feedback[0])
    feedback_2.append(all_feedback[1])
    feedback_3.append(all_feedback[2])
    feedback_4.append(all_feedback[3])
    feedback_5.append(all_feedback[4])
    feedback_6.append(all_feedback[5])
    feedback_7.append(all_feedback[6])
    
analysis_v2[question_14_1] = feedback_1
analysis_v2[question_14_2] = feedback_2
analysis_v2[question_14_3] = feedback_3
analysis_v2[question_14_4] = feedback_4
analysis_v2[question_14_5] = feedback_5
analysis_v2[question_14_6] = feedback_6
analysis_v2[question_14_7] = feedback_7

In [86]:
analysis_v2.head()

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,DoDiff6,DoDiff7,ContributeMe,Contribute1,Contribute2,Contribute3,Contribute4,Contribute5,Contribute6,Contribute7
0,Arush Godha,arush.godha@berkeley.edu,1,1,7.0,6.8,6.1,1.1,7.0,6.2,...,I would like us to set better deadlines.,NaN,Working well towards ideation,Working well towards ideation,No Response,Helped build some part of the 3D printer,No Response,No Response,speaks well,
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2,NaN,6.8,6.1,1.1,NaN,6.2,...,I would like us to set better deadlines.,NaN,No Response,Working well towards product design,No Response,Helped with most of the development of the tel...,No Response,No Response,takes charge,
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3,6.0,6.8,6.1,1.1,5.0,6.2,...,I would like us to set better deadlines.,NaN,Helped with a lot of aspects and delvelopment ...,Working well towards product design,No Response,Helped with a lot of aspects and delvelopment ...,No Response,No Response,helps a lot,
3,Khant Nyi,knyi@berkeley.edu,1,4,7.0,6.8,6.1,1.1,6.0,6.2,...,I would like us to set better deadlines.,NaN,No Response,Working well towards product design,No Response,Helped build the 3D printer and brings new sol...,No Response,No Response,helps a lot,
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5,NaN,6.8,6.1,1.1,NaN,6.2,...,I would like us to set better deadlines.,NaN,No Response,Working well towards product design,No Response,Provides solutions to problems we faced and le...,No Response,No Response,does a lot of skek,

### 24

In [143]:
#24.1 (GPT me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '24.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_24_me = question_shorthand[24][0]
analysis_v2[question_24_me] = lst_responses

In [144]:
#24 (GPT version of 14)

question_24_1 = question_shorthand[24][1]
question_24_2 = question_shorthand[24][2]
question_24_3 = question_shorthand[24][3]
question_24_4 = question_shorthand[24][4]
question_24_5 = question_shorthand[24][5]
question_24_6 = question_shorthand[24][6]
question_24_7 = question_shorthand[24][7]

feedback_1 = []
feedback_2 = []
feedback_3 = []
feedback_4 = []
feedback_5 = [] 
feedback_6 = []
feedback_7 = []#need to adjust to max team size


for i in range(len(full_cleaned_data)):
    my_teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    my_team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_number_str = str(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == my_team_number]
    list_feedback_for_me = list(my_team_df["24." + str(my_teammate_number)])
    num_teammates = len(list_feedback_for_me)
    extra_needed = 7 - num_teammates
    placeholders = [''] * extra_needed
    all_feedback = list_feedback_for_me + placeholders

    feedback_1.append(all_feedback[0])
    feedback_2.append(all_feedback[1])
    feedback_3.append(all_feedback[2])
    feedback_4.append(all_feedback[3])
    feedback_5.append(all_feedback[4])
    feedback_6.append(all_feedback[5])
    feedback_7.append(all_feedback[6])
    
analysis_v2[question_24_1] = feedback_1
analysis_v2[question_24_2] = feedback_2
analysis_v2[question_24_3] = feedback_3
analysis_v2[question_24_4] = feedback_4
analysis_v2[question_24_5] = feedback_5
analysis_v2[question_24_6] = feedback_6
analysis_v2[question_24_7] = feedback_7

### 15

In [87]:
#15.1 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '15.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_15_me = question_shorthand[15][0]
analysis_v2[question_15_me] = lst_responses

In [88]:
#15

question_15_1 = question_shorthand[15][1]
question_15_2 = question_shorthand[15][2]
question_15_3 = question_shorthand[15][3]
question_15_4 = question_shorthand[15][4]
question_15_5 = question_shorthand[15][5]
question_15_6 = question_shorthand[15][6]
question_15_7 = question_shorthand[15][7]

feedback_1 = []
feedback_2 = []
feedback_3 = []
feedback_4 = []
feedback_5 = [] 
feedback_6 = []
feedback_7 = []#need to adjust to max team size

#possibilities = ["14.1", "14.2", "14.3", "14.4", "14.5", "14.6"]
for i in range(len(full_cleaned_data)):
    my_teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    my_team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_number_str = str(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == my_team_number]
    list_feedback_for_me = list(my_team_df["15." + str(my_teammate_number)])
    num_teammates = len(list_feedback_for_me)
    extra_needed = 7 - num_teammates
    placeholders = [''] * extra_needed
    all_feedback = list_feedback_for_me + placeholders

    feedback_1.append(all_feedback[0])
    feedback_2.append(all_feedback[1])
    feedback_3.append(all_feedback[2])
    feedback_4.append(all_feedback[3])
    feedback_5.append(all_feedback[4])
    feedback_6.append(all_feedback[5])
    feedback_7.append(all_feedback[6])
    
analysis_v2[question_15_1] = feedback_1
analysis_v2[question_15_2] = feedback_2
analysis_v2[question_15_3] = feedback_3
analysis_v2[question_15_4] = feedback_4
analysis_v2[question_15_5] = feedback_5
analysis_v2[question_15_6] = feedback_6
analysis_v2[question_15_7] = feedback_7

### 25

In [145]:
#25.1 (GPT me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '25.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_25_me = question_shorthand[25][0]
analysis_v2[question_25_me] = lst_responses

In [146]:
#25 (GPT version of 15)

question_25_1 = question_shorthand[25][1]
question_25_2 = question_shorthand[25][2]
question_25_3 = question_shorthand[25][3]
question_25_4 = question_shorthand[25][4]
question_25_5 = question_shorthand[25][5]
question_25_6 = question_shorthand[25][6]
question_25_7 = question_shorthand[25][7]

feedback_1 = []
feedback_2 = []
feedback_3 = []
feedback_4 = []
feedback_5 = [] 
feedback_6 = []
feedback_7 = []#need to adjust to max team size


for i in range(len(full_cleaned_data)):
    my_teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    my_team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_number_str = str(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == my_team_number]
    list_feedback_for_me = list(my_team_df["25." + str(my_teammate_number)])
    num_teammates = len(list_feedback_for_me)
    extra_needed = 7 - num_teammates
    placeholders = [''] * extra_needed
    all_feedback = list_feedback_for_me + placeholders

    feedback_1.append(all_feedback[0])
    feedback_2.append(all_feedback[1])
    feedback_3.append(all_feedback[2])
    feedback_4.append(all_feedback[3])
    feedback_5.append(all_feedback[4])
    feedback_6.append(all_feedback[5])
    feedback_7.append(all_feedback[6])
    
analysis_v2[question_25_1] = feedback_1
analysis_v2[question_25_2] = feedback_2
analysis_v2[question_25_3] = feedback_3
analysis_v2[question_25_4] = feedback_4
analysis_v2[question_25_5] = feedback_5
analysis_v2[question_25_6] = feedback_6
analysis_v2[question_25_7] = feedback_7

### 16

In [89]:

#16 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '16.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_16_me = question_shorthand[16][0]
analysis_v2[question_16_me] = lst_responses

In [90]:
#Question 16 team average
question_16_tm_avg = question_shorthand[16][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '16.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))
analysis_v2[question_16_tm_avg] = lst_responses

In [93]:
# #Question 16 class avg
question_16_class_avg = question_shorthand[16][2]
class_avg = np.nanmean(full_cleaned_data[["16.1", "16.2", "16.3", "16.4", "16.5", "16.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_16_class_avg] = round(class_avg, 1)

In [94]:
# #Question 16 class std
question_16_class_std = question_shorthand[16][3]
class_std_arr = full_cleaned_data[["16.1", "16.2", "16.3", "16.4", "16.5", "16.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_16_class_std] = round(np.std(class_std_arr_no_na), 1)

### 17

In [95]:
# #17 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '17.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_17_me = question_shorthand[17][0]
analysis_v2[question_17_me] = lst_responses

In [96]:
# #Question 17 team average
question_17_tm_avg = question_shorthand[17][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '17.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_17_tm_avg] = lst_responses

In [97]:
#analysis_v2

In [98]:
# #Question 17 class avg
question_17_class_avg = question_shorthand[17][2]
class_avg = np.nanmean(full_cleaned_data[["17.1", "17.2", "17.3", "17.4", "17.5", "17.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_17_class_avg] = round(class_avg, 1)

In [99]:
# #Question 17 class std
question_17_class_std = question_shorthand[17][3]
class_std_arr = full_cleaned_data[["17.1", "17.2", "17.3", "17.4", "17.5", "17.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_17_class_std] = round(np.std(class_std_arr_no_na), 1)

### 18

In [100]:
# #18 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '18.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_18_me = question_shorthand[18][0] 
analysis_v2[question_18_me] = lst_responses

In [101]:
# #Question 18 team average
question_18_tm_avg = question_shorthand[18][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '18.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_18_tm_avg] = lst_responses

In [102]:
# #Question 18 class avg
question_18_class_avg = question_shorthand[18][2]
class_avg = np.nanmean(full_cleaned_data[["18.1", "18.2", "18.3", "18.4", "18.5", "18.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_18_class_avg] = round(class_avg, 1)

In [103]:
# #Question 18 class std
question_18_class_std = question_shorthand[18][3]
class_std_arr = full_cleaned_data[["18.1", "18.2", "18.3", "18.4", "18.5", "18.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_18_class_std] = round(np.std(class_std_arr_no_na), 1)

### 19

In [104]:
# #19 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '19.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_19_me = question_shorthand[19][0]
analysis_v2[question_19_me] = lst_responses

In [105]:
# #Question 19 team average
question_19_tm_avg = question_shorthand[19][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '19.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_19_tm_avg] = lst_responses

In [106]:
# #Question 19 class avg
question_19_class_avg = question_shorthand[19][2]
class_avg = np.nanmean(full_cleaned_data[["19.1", "19.2", "19.3", "19.4", "19.5", "19.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_19_class_avg] = round(class_avg, 1)

In [107]:
# #Question 19 class std
question_19_class_std = question_shorthand[19][3]
class_std_arr = full_cleaned_data[["19.1", "19.2", "19.3", "19.4", "19.5", "19.6"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_19_class_std] = round(np.std(class_std_arr_no_na), 1)

## Add extra questions

In [108]:
full_cleaned_data.columns

Index(['index', 'Unnamed: 0', 'Email', 'TeamNumber', 'TeammateNumber',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail', '2.1',
       '2.2', '2.3', '3', '4.1', '4.5', '4.6', '4.2', '4.3', '4.4', '4.7',
       '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '6', '7', '16.1',
       '16.2', '16.3', '16.4', '16.5', '16.6', '16.7', '17.1', '17.2', '17.3',
       '17.4', '17.5', '17.6', '17.7', '18.1', '18.2', '18.3', '18.4', '18.5',
       '18.6', '18.7', '19.1', '19.2', '19.3', '19.4', '19.5', '19.6', '19.7',
       '14.1', '14.2', '14.3', '14.4', '14.5', '14.6', '14.7', '15.1', '15.2',
       '15.3', '15.4', '15.5', '15.6', '15.7'],
      dtype='object')

In [148]:

#analysis_v2[question_shorthand[38.1]] = full_cleaned_data["38.1"]
##analysis_v2[question_shorthand[38.2]] = full_cleaned_data["38.2"]
#analysis_v2[question_shorthand[38.3]] = full_cleaned_data["38.3"]
#analysis_v2["Q25"] = full_cleaned_data['33']
#analysis_v2["What did you learn from the first check-in survey feedback?"] = full_cleaned_data['57']
#analysis_v2["Q33_TEXT"] = full_cleaned_data['33.4.TEXT']
analysis_v2['20.1'] = full_cleaned_data['20.1']
analysis_v2['20.2'] = full_cleaned_data['20.2']
analysis_v2['20.3'] = full_cleaned_data['20.3']
analysis_v2['20.4'] = full_cleaned_data['20.4']
analysis_v2['20.5'] = full_cleaned_data['20.5']
analysis_v2['20.6'] = full_cleaned_data['20.6']
analysis_v2['20.7'] = full_cleaned_data['20.7']
analysis_v2['20.8'] = full_cleaned_data['20.8']
analysis_v2['20.9'] = full_cleaned_data['20.9']
analysis_v2['20.10'] = full_cleaned_data['20.10']
analysis_v2['20.11'] = full_cleaned_data['20.11']
analysis_v2['20.12'] = full_cleaned_data['20.12']
analysis_v2['20.13'] = full_cleaned_data['20.13']
analysis_v2['20.14'] = full_cleaned_data['20.14']
analysis_v2['20.15'] = full_cleaned_data['20.15']
analysis_v2['20.16'] = full_cleaned_data['20.16']
analysis_v2['20.17'] = full_cleaned_data['20.17']
analysis_v2['20.18'] = full_cleaned_data['20.18']
analysis_v2['20.19'] = full_cleaned_data['20.19']
analysis_v2['20.20'] = full_cleaned_data['20.20']
analysis_v2['21.1'] = full_cleaned_data['21.1']
analysis_v2['21.2'] = full_cleaned_data['21.2']
analysis_v2['21.3'] = full_cleaned_data['21.3']
analysis_v2['21.4'] = full_cleaned_data['21.4']
analysis_v2['21.5'] = full_cleaned_data['21.5']
analysis_v2['21.6'] = full_cleaned_data['21.6']
analysis_v2['21.7'] = full_cleaned_data['21.7']
analysis_v2['21.8'] = full_cleaned_data['21.8']
analysis_v2['21.9'] = full_cleaned_data['21.9']
analysis_v2['21.10'] = full_cleaned_data['21.10']
analysis_v2['21.11'] = full_cleaned_data['21.11']
analysis_v2['21.12'] = full_cleaned_data['21.12']
analysis_v2['21.13'] = full_cleaned_data['21.13']
analysis_v2['21.14'] = full_cleaned_data['21.14']
analysis_v2['21.15'] = full_cleaned_data['21.15']
analysis_v2['21.16'] = full_cleaned_data['21.16']
analysis_v2['21.17'] = full_cleaned_data['21.17']
analysis_v2['21.18'] = full_cleaned_data['21.18']
analysis_v2['21.19'] = full_cleaned_data['21.19']
analysis_v2['21.20'] = full_cleaned_data['21.20']
analysis_v2["Q99"] = full_cleaned_data['99']

In [86]:
analysis_v2['25_1']=full_cleaned_data['25.1']
analysis_v2['25_2']=full_cleaned_data['25.2']
analysis_v2['25_3']=full_cleaned_data['25.3']
analysis_v2['26']=full_cleaned_data['26']

In [87]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,DoDiff2,DoDiff3,DoDiff4,DoDiff5,DoDiff6,DoDiff7,25_1,25_2,25_3,26
0,Arush Godha,arush.godha@berkeley.edu,1,1,NaN,6.0,6.1,1.0,NaN,6.0,...,Continue strong communication with the team.,No Response,most of us had come up with different ideas (c...,No Response,No Response,NaN,No Response,No Response,No Response,No Response
1,Aaron Lee,aaronlee5702@berkeley.edu,1,2,6.0,6.0,6.1,1.0,6.0,6.0,...,Continue strong communication with the team.,No Response,most of us had come up with different ideas (c...,No Response,No Response,NaN,I'm doing better,I'm doing better,I'm doing better,I will be aware and listen more to my team.
2,Naomi Nogueira,naomi_nogueira@berkeley.edu,1,3,NaN,6.0,6.1,1.0,NaN,6.0,...,Continue strong communication with the team.,No Response,most of us had come up with different ideas (c...,No Response,No Response,NaN,No Response,No Response,No Response,No Response
3,Khant Nyi,knyi@berkeley.edu,1,4,6.0,6.0,6.1,1.0,6.0,6.0,...,Continue strong communication with the team.,No Response,most of us had come up with different ideas (c...,No Response,No Response,NaN,I'm doing about the same,I'm doing about the same,I've let this one slide a little,I would try to contribute more than before to ...
4,Brandon Ramos-Bailon,bramos6837@berkeley.edu,1,5,NaN,6.0,6.1,1.0,NaN,6.0,...,Continue strong communication with the team.,No Response,most of us had come up with different ideas (c...,No Response,No Response,NaN,No Response,No Response,No Response,No Response
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Pablo Brunet,pbrunet@berkeley.edu,30,2,6.0,6.2,6.1,1.0,6.0,6.2,...,Be more proactive about starting work by each ...,Attendance,We should meet up more often / send updates,I think if there's multiple tasks to do we hav...,More urgency in completing tasks.,NaN,I'm doing better,I'm doing about the same,I'm doing better,I think after each lab we should have a list o...
168,Eilyn Garcia,garciaeilyn@berkeley.edu,30,3,7.0,6.2,6.1,1.0,7.0,6.2,...,Be more proactive about starting work by each ...,Attendance,We should meet up more often / send updates,I think if there's multiple tasks to do we hav...,More urgency in completing tasks.,NaN,I'm doing better,I'm doing better,I'm doing better,To pay more attention to reach our team goals
169,Tiffelyn Kurniawan,tifkurnia2004@berkeley.edu,30,4,7.0,6.2,6.1,1.0,7.0,6.2,...,Be more proactive about starting work by each ...,Attendance,We should meet up more often / send updates,I think if there's multiple tasks to do we hav...,More urgency in completing tasks.,NaN,I'm doing better,I'm doing better,I'm doing better,I would like to state my opinion more
170,Eric Lind,elind1@berkeley.edu,30,5,4.0,6.2,6.1,1.0,4.0,6.2,...,Be more proactive about starting work by each ...,Attendance,We should meet up more often / send updates,I think if there's multiple tasks to do we hav...,More urgency in completing tasks.,NaN,I'm doing about the same,I'm doing about the same,I'm doing about the same,I need to be better and showing up to team mee...
171,Brandon Wong,wongton@berkeley.edu,30,6,6.0,6.2,6.1,1.0,6.0,6.2,...,Be more proactive about starting work by each ...,Attendance,We should meet up more often / send updates,I think if there's multiple tasks to do we hav...,More urgency in completing tasks.,NaN,I'm doing better,I'm doing better,I'm doing better,No Response

In [109]:
analysis_v2.to_csv("E29_CHECKIN03_MACROANALYSIS_V1.csv")