In [1]:
import pandas as pd
import numpy as np
import stat
import re
import warnings
warnings.filterwarnings("ignore")

In [2]:
#cd 'cleaning'

In [3]:
#analysis = pd.read_csv("FF_HEALTH_DC3_ANALYSIS.csv")
roster = pd.read_csv("E29_Qualtrics_Roster_EOS.CSV")
dictionary = pd.read_csv("E29_QUESTION_DICTIONARY.csv")
raw = pd.read_csv("E29_PRECLEAN_CHECKIN03_RAW_TEXT.csv")

full_cleaned_data = pd.read_csv("full_cleaned.csv")

In [4]:
full_cleaned_data

,Unnamed: 0,Email,TeamNumber,TeammateNumber,RecipientLastName,RecipientFirstName,RecipientEmail,33,39.1,39.2,...,18.4,19.1,19.2,19.3,19.4,55,51,52,53,54
0,0,allanzhong@berkeley.edu,Team 1,1.0,Zhong,Allan,allanzhong@berkeley.edu,Yes,4,3.5,...,6.0,6.0,6.0,6.0,6.0,No Response,No Response,No Response,No Response,No Response
1,1,eclopez19@berkeley.edu,Team 1,2.0,No Response,No Response,No Response,No Response,No Response,No Response,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response
2,2,jerrick@berkeley.edu,Team 1,3.0,Wang,Jerrick,jerrick@berkeley.edu,Yes,4.5,4.5,...,7.0,7.0,7.0,7.0,7.0,5,How to work in a team better,How to do more manufacturing,How to combine technical and interpersonal skills,I could do more technical or manufacturing
3,3,simrankk@berkeley.edu,Team 1,4.0,Kaur Khahira,Simran,simrankk@berkeley.edu,Yes,3.5,4,...,5.0,3.0,3.0,4.0,5.0,No Response,technical skills,more ways to improve,final result,had more time
4,4,miroygarrett@berkeley.edu,Team 10,1.0,Garrett,Miro,miroygarrett@berkeley.edu,Yes,4,5,...,7.0,5.0,7.0,7.0,7.0,5,about applications of GD&T and about my teammates,if we will consider continuing to pursue this ...,how well received our product and prototype were,we came up with the idea for the product earlier.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,128,siddhant.vasudevan@berkeley.edu,Team 8,4.0,No Response,No Response,No Response,No Response,No Response,No Response,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response
129,129,allan.sram16@berkeley.edu,Team 9,1.0,No Response,No Response,No Response,No Response,No Response,No Response,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response
130,130,arnavp45@berkeley.edu,Team 9,2.0,Patel,Arnav,arnavp45@berkeley.edu,Yes,4,4,...,7.0,7.0,7.0,7.0,7.0,No Response,about the effort it takes do develop a product...,how this process will be different in the indu...,how easy it was to work when everybody was on ...,we did not have as many tedious assignments
131,131,owenlachs@berkeley.edu,Team 9,3.0,Lachs,Owen,owenlachs@berkeley.edu,Yes,4,4.5,...,7.0,7.0,7.0,7.0,6.0,5,my natural role on a team of engineers.,How I would perform in a different role on the...,the fact that there was no struggle for power ...,I got more time to develop the project to make...
132,132,tyler.peng@berkeley.edu,Team 9,4.0,Peng,Tyler,tyler.peng@berkeley.edu,Yes,1.5,1.5,...,7.0,7.0,7.0,7.0,7.0,No Response,How to make product with team,How we could have improved,A working product,We had more people

In [5]:
quant = [str(x) for x in list(dictionary[dictionary["type"] == 'quantitative']["question_id"])]

numerical_data = full_cleaned_data[['TeamNumber', 'TeammateNumber','2.1',
 '2.2',
 '2.3',
 '4.1',
 '4.2',
 '4.3',
 '4.4',
 '5.1',
 '5.2',
 '5.3',
 '5.4',
 '16.1',
 '16.2',
 '16.3',
 '16.4',
 '17.1',
 '17.2',
 '17.3',
 '17.4',
 '18.1',
 '18.2',
 '18.3',
 '18.4',
 '19.1',
 '19.2',
 '19.3',
 '19.4']]
numerical_data = numerical_data.replace({"No Response" : np.nan})
numerical_data.head()

,TeamNumber,TeammateNumber,2.1,2.2,2.3,4.1,4.2,4.3,4.4,5.1,...,17.3,17.4,18.1,18.2,18.3,18.4,19.1,19.2,19.3,19.4
0,Team 1,1.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,27,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
1,Team 1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Team 1,3.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,25,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
3,Team 1,4.0,6.0,6.0,5.0,6.0,5.0,5.0,4.0,40,...,5.0,5.0,7.0,3.0,5.0,5.0,3.0,3.0,4.0,5.0
4,Team 10,1.0,6.0,5.0,7.0,6.0,5.0,6.0,7.0,25,...,6.0,7.0,6.0,7.0,7.0,7.0,5.0,7.0,7.0,7.0

In [6]:
numerical_data["TeamNumber"] = [float(team.replace("Team", '').strip()) for team in numerical_data["TeamNumber"]]
full_cleaned_data["TeamNumber"] = [float(team.replace("Team", '').strip()) for team in full_cleaned_data["TeamNumber"]]
roster["TeamNumber"] = [float(team.replace("Team", '').strip()) for team in roster["TeamNumber"]]
roster["TeammateNumber"] = roster["TeammateNumber"].astype(float)

In [7]:
numerical_data = numerical_data.astype(float)
numerical_data["Email"] = full_cleaned_data["Email"]
numerical_data = numerical_data.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index()
full_cleaned_data = full_cleaned_data.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index()
roster = roster.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index()

In [8]:
roster.head()

,index,Index,FullName,First name,Last Name,Email,TeamNumber,TeammateNumber,Teammate1,Teammate2,Teammate3,Teammate4,SharedGoal_Checkin1,SharedGoal_Checkin2,TopInterest1,TopInterest2,TopInterest3
0,0,0,Allan Zhong,Allan,Zhong,allanzhong@berkeley.edu,1.0,1.0,Allan Zhong,Edwin Lopez,Jerrick Wang,Simran Kaur Khahira,"Our shared goals are open communication, quali...","open communication, equal workload, friendly a...",I encourage others on the team to contribute,"I help my team adhere to schedules, e.g., enga...",I help my teammates recognize the value of the...
1,1,1,Edwin Lopez,Edwin,Lopez,eclopez19@berkeley.edu,1.0,2.0,Allan Zhong,Edwin Lopez,Jerrick Wang,Simran Kaur Khahira,Everyone contributing their fair share of work...,NaN,I do a fair share of the work,I communicate information and feelings clearly,I facilitate exchange of ideas among my teammates
2,2,2,Jerrick Wang,Jerrick,Wang,jerrick@berkeley.edu,1.0,3.0,Allan Zhong,Edwin Lopez,Jerrick Wang,Simran Kaur Khahira,Collaborate to generate a gearbox design that ...,Redesign a new product with comparable quality...,I communicate information and feelings clearly,"I help my team adhere to schedules, e.g., enga...",I help my teammates recognize the value of the...
3,3,3,Simran Kaur Khahira,Simran,Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,Allan Zhong,Edwin Lopez,Jerrick Wang,Simran Kaur Khahira,Team Goal would be to efficiently work togethe...,"Well our project has changed, so the goal now ...",I teach my teammates how to do elements of the...,I encourage my team to set aside time for feed...,I help my teammates recognize the value of the...
4,42,42,Ashley De Jesus,Ashley,De Jesus,adejesus22@berkeley.edu,2.0,1.0,Ashley De Jesus,Ian Lind,Rohan Karra,Rolando Torres,Our goals our to be open with communication an...,To find a way to better our project and be col...,I make sure that my teammates understand me an...,"I help my team adhere to schedules, e.g., enga...",I encourage my team to set aside time for feed...

In [9]:
numerical_data

,index,TeamNumber,TeammateNumber,2.1,2.2,2.3,4.1,4.2,4.3,4.4,...,17.4,18.1,18.2,18.3,18.4,19.1,19.2,19.3,19.4,Email
0,0,1.0,1.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,allanzhong@berkeley.edu
1,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eclopez19@berkeley.edu
2,2,1.0,3.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,jerrick@berkeley.edu
3,3,1.0,4.0,6.0,6.0,5.0,6.0,5.0,5.0,4.0,...,5.0,7.0,3.0,5.0,5.0,3.0,3.0,4.0,5.0,simrankk@berkeley.edu
4,42,2.0,1.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,adejesus22@berkeley.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,105,34.0,4.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,yousufabubakr123@berkeley.edu
129,106,35.0,1.0,7.0,6.0,6.0,7.0,7.0,7.0,7.0,...,7.0,7.0,7.0,7.0,7.0,6.0,6.0,6.0,6.0,avinashsrikanth@berkeley.edu
130,107,35.0,2.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,...,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,ianpb@berkeley.edu
131,108,35.0,3.0,7.0,7.0,6.0,7.0,6.0,7.0,6.0,...,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,vnandita11@berkeley.edu
132,109,35.0,4.0,7.0,6.0,6.0,6.0,5.0,7.0,5.0,...,6.0,5.0,6.0,6.0,6.0,5.0,6.0,6.0,6.0,samuel.mankoff@berkeley.edu

In [10]:
#Functions 

def calculate_team_averages(df):
    # Creates a DataFrame with the averages per team for each question
    return df.groupby("TeamNumber").agg(np.nanmean)[numerical_questions]

def get_team_data(team_number):
    # Returns new dataframe containing only TEAM_NUMBER's data
    return numerical_data[numerical_data['TeamNumber'] == team_number]

def get_team_average(team_number, question):
    # Gets TEAM_NUMBER's average on the specified question
    temp_df = get_team_data(team_number)
    return np.nanmean(temp_df[question])

def get_team_std(team_number, teammate_number, question):
    # Gets TEAM_NUMBER's standard deviation on the specified question and should not include self
    temp_df = get_team_data(team_number)
    temp_df = temp_df[temp_df['TeammateNumber'] != teammate_number]
    
    return np.nanstd(temp_df[question])

def get_teammates_average(team_number, teammate_number, question):
    # Gets TEAM_NUMBER's average on the specified question
    # omits data from current student given by TEAMMATE_NUMBER 
    temp_df = get_team_data(team_number)
    
    temp_df = temp_df[temp_df['TeammateNumber'] != teammate_number]
    
    return np.nanmean(temp_df[question])


def get_student_answer(team_number, teammate_number, question):
    # Returns the current student's response for the specified question
    temp_df = get_team_data(team_number)
    
    temp_df = temp_df[temp_df['TeammateNumber'] == teammate_number]
    
    return float(temp_df[question])
    #return temp_df[question]

def get_class_average(question):
    # Returns the class average for QUESTION
    return np.mean(numerical_data[question])

def get_class_stdv(question):
    # Returns the class std dev for QUESTION
    return np.std(numerical_data[question])

## Part 1: Identification Information

In [11]:
#roster = roster.rename({"FullName": "Full Name"}, axis=1)

In [12]:
analysis_v2 = roster[["FullName", "Email", "TeamNumber", "TeammateNumber"]]

In [13]:
analysis_v2 = analysis_v2.sort_values(["TeamNumber", "TeammateNumber"], ascending=True).reset_index(drop=True)

In [14]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0
...,...,...,...,...
128,Yousuf Abubakr,yousufabubakr123@berkeley.edu,34.0,4.0
129,Avinash Srikanth,avinashsrikanth@berkeley.edu,35.0,1.0
130,Ian Bolano,ianpb@berkeley.edu,35.0,2.0
131,Nandita Venkataraman,vnandita11@berkeley.edu,35.0,3.0
132,Samuel Mankoff,samuel.mankoff@berkeley.edu,35.0,4.0

## Part 2: Skills Assessment

In [15]:
...

Ellipsis

## Part 3: Survey Questionnairre

In [16]:
question_shorthand = {}
question_shorthand[2.1] = ['SharedGoalTeamAvg', 'SharedGoalClassAvg', 'SharedGoalClassStDev']
question_shorthand[2.2] = ['IndvGoalTeamAvg', 'IndvGoalClassAvg', 'IndvGoalClassStDev']
question_shorthand[2.3] = ['SupportTeamAvg', 'SupportClassAvg', 'SupportClassStDev']
question_shorthand[3.0] = ['Goal1', 'Goal2', 'Goal3', 'Goal4']
question_shorthand[4.1] = ['CommunicateTeamAvg', 'CommunicateClassAvg', 'CommunicateClassStDev']
question_shorthand[4.2] = ['WorkAllocTeamAvg', 'WorkAllocClassAvg', 'WorkAllocClassStDev']
question_shorthand[4.3] = ['RoleTeamAvg', 'RoleClassAvg', 'RoleClassStDev']
question_shorthand[4.4] = ['EnjoyTeamAvg', 'EnjoyClassAvg', 'EnjoyClassStDev']
question_shorthand[5.0] = ['MyPoints', 'TeammateAvgPoints', 'ExpectedPoints', 'Percent', 'AveragePointsAllocated', 'StDevPointsAllocated']
question_shorthand[5.1] = 'Work Contribution Teammate 1'
question_shorthand[5.2] = 'Work Contribution Teammate 2'
question_shorthand[5.3] = 'Work Contribution Teammate 3'
question_shorthand[5.4] = 'Work Contribution Teammate 4'
#question_shorthand[5.5] = 'Work Contribution Teammate 5'
#question_shorthand[5.6] = 'Work Contribution Teammate 6' #might need to increase this based on team size
question_shorthand[6.0] = ['DidWellMe','DidWell1','DidWell2','DidWell3','DidWell4']
question_shorthand[7] = ['DoDiffMe', 'DoDiff1', 'DoDiff2', 'DoDiff3', 'DoDiff4']
#question_shorthand[9.1] = 'ImproveAmt1'
#question_shorthand[9.2] = 'ImproveAmt2'
#question_shorthand[9.3] = 'ImproveAmt3'
#question_shorthand[10.1] = ["AskFeedbackClassAvg", "AskFeedbackClassStDev"]
#question_shorthand[10.2] = ["AskHelpClassAvg", "AskHelpClassStDev"]
#question_shorthand[10.3] = ["ValueContrClassAvg", "ValueContrClassStdev"]
#question_shorthand[10.4] = ["ReflectClassAvg", "ReflectClassStDev"]
#questions 11-13 are just imported as questions themselves as columns
question_shorthand[14] = ["ContributeMe", "Contribute1", "Contribute2", "Contribute3", "Contribute4"]
question_shorthand[15] = ['ImproveMe', 'Improve1', 'Improve2', 'Improve3', 'Improve4']
question_shorthand[16] = ['InitiativeMe', 'InitiativeTeammateAvg', 'InitiativeClassAvg', 'InitiativeClassStDev']
question_shorthand[17] = ['CommunicateMe', 'CommunicateTeammateAvg', 'Communicate2ClassAvg', 'Communicate2ClassStDev']
question_shorthand[18] = ['ExpertiseMe', 'ExpertiseTeammateAvg', 'ExpertiseClassAvg', 'ExpertiseClassStDev']
question_shorthand[19] = ['RespectMe', 'RespectTeammateAvg', 'RespectClassAvg', 'RespectClassStDev']
question_shorthand[38.1] = 'ImproveAmt1'
question_shorthand[38.2] = 'ImproveAmt2'
question_shorthand[38.3] = 'ImproveAmt3'

### 2.1

In [17]:
#Question 2.1

question_2_1 = dictionary[dictionary["question_id"] == 2.1].reset_index()["question"][0]
analysis_v2[question_2_1] = numerical_data["2.1"]

In [18]:
#Question 2.1 team average
question_2_1_0 = question_shorthand[2.1][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "2.1"), 1))

analysis_v2[question_2_1_0] = lst_responses

In [19]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0,6.0,6.3
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0,NaN,6.3
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0,7.0,6.3
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,6.0,6.3
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0,6.0,6.5
...,...,...,...,...,...,...
128,Yousuf Abubakr,yousufabubakr123@berkeley.edu,34.0,4.0,6.0,6.0
129,Avinash Srikanth,avinashsrikanth@berkeley.edu,35.0,1.0,7.0,7.0
130,Ian Bolano,ianpb@berkeley.edu,35.0,2.0,7.0,7.0
131,Nandita Venkataraman,vnandita11@berkeley.edu,35.0,3.0,7.0,7.0
132,Samuel Mankoff,samuel.mankoff@berkeley.edu,35.0,4.0,7.0,7.0

In [20]:
#Question 2.1 class avg
question_2_1_1 = question_shorthand[2.1][1]

analysis_v2[question_2_1_1] = round(get_class_average("2.1"), 1)

In [21]:


#Question 2.1 class std
question_2_1_2 = question_shorthand[2.1][2]

analysis_v2[question_2_1_2] = round(get_class_stdv("2.1"), 1)

In [22]:
#analysis_v2.iloc[97]

### 2.2

In [23]:
#Question 2.2

question_2_2 = dictionary[dictionary["question_id"] == 2.2].reset_index()["question"][0]
analysis_v2[question_2_2] = numerical_data["2.2"]

In [24]:
#Question 2.2 team average
question_2_2_0 = question_shorthand[2.2][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "2.2"), 1))

analysis_v2[question_2_2_0] = lst_responses

In [25]:
#Question 2.2 class avg
question_2_2_1 = question_shorthand[2.2][1]

analysis_v2[question_2_2_1] = round(get_class_average("2.2"), 1)

In [26]:
#Question 2.2 class std
question_2_2_2 = question_shorthand[2.2][2]

analysis_v2[question_2_2_2] = round(get_class_stdv("2.2"), 1)

In [27]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,IndvGoalClassAvg,IndvGoalClassStDev
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0,6.0,6.3,6.4,0.9,6.0,6.3,6.3,0.9
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0,NaN,6.3,6.4,0.9,NaN,6.3,6.3,0.9
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0,7.0,6.3,6.4,0.9,7.0,6.3,6.3,0.9
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,6.0,6.3,6.4,0.9,6.0,6.3,6.3,0.9
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0,6.0,6.5,6.4,0.9,6.0,6.2,6.3,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...
128,Yousuf Abubakr,yousufabubakr123@berkeley.edu,34.0,4.0,6.0,6.0,6.4,0.9,6.0,6.0,6.3,0.9
129,Avinash Srikanth,avinashsrikanth@berkeley.edu,35.0,1.0,7.0,7.0,6.4,0.9,6.0,6.5,6.3,0.9
130,Ian Bolano,ianpb@berkeley.edu,35.0,2.0,7.0,7.0,6.4,0.9,7.0,6.5,6.3,0.9
131,Nandita Venkataraman,vnandita11@berkeley.edu,35.0,3.0,7.0,7.0,6.4,0.9,7.0,6.5,6.3,0.9
132,Samuel Mankoff,samuel.mankoff@berkeley.edu,35.0,4.0,7.0,7.0,6.4,0.9,6.0,6.5,6.3,0.9

### 2.3

In [28]:
#Question 2.3

question_2_3 = dictionary[dictionary["question_id"] == 2.3].reset_index()["question"][0]
analysis_v2[question_2_3] = numerical_data["2.3"]

In [29]:
#Question 2.3 team average
question_2_3_0 = question_shorthand[2.3][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "2.3"), 1))

analysis_v2[question_2_3_0] = lst_responses

In [30]:
#Question 2.3 class avg
question_2_3_1 = question_shorthand[2.3][1]

analysis_v2[question_2_3_1] = round(get_class_average("2.3"), 1)

In [31]:
#Question 2.3 class std
question_2_3_2 = question_shorthand[2.3][2]

analysis_v2[question_2_3_2] = round(get_class_stdv("2.3"), 1)

### 3

In [32]:
question_3 = dictionary[dictionary["question_id"] == 3.0].reset_index()["question"][0]

In [33]:
analysis_v2[question_3] = full_cleaned_data["3"]

In [34]:
#goal 1
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 1].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_1 = question_shorthand[3.0][0]
analysis_v2[question_3_1] = lst_responses

In [35]:
#goal 2
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 2].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_2 = question_shorthand[3.0][1]
analysis_v2[question_3_2] = lst_responses

In [36]:
#goal 3
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 3].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_3 = question_shorthand[3.0][2]
analysis_v2[question_3_3] = lst_responses

In [37]:
#goal 4
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    df_question_at_hand = team_df[team_df["TeammateNumber"] == 4].reset_index()["3"]
    if len(df_question_at_hand) == 0:
        lst_responses.append(np.nan)
    else:
        lst_responses.append(df_question_at_hand[0])
    
question_3_4 = question_shorthand[3.0][3]
analysis_v2[question_3_4] = lst_responses

### 4.1

In [38]:
#Question 4.1

question_4_1 = dictionary[dictionary["question_id"] == 4.1].reset_index()["question"][0]
analysis_v2[question_4_1] = numerical_data["4.1"]

In [39]:
#analysis_v2

In [40]:
#Question 4.1 team average
question_4_1_0 = question_shorthand[4.1][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.1"), 1))

analysis_v2[question_4_1_0] = lst_responses

In [41]:
#analysis_v2

In [42]:
#Question 4.1 class avg
question_4_1_1 = question_shorthand[4.1][1]

analysis_v2[question_4_1_1] = round(get_class_average("4.1"), 1)

In [43]:
#Question 4.1 class std
question_4_1_2 = question_shorthand[4.1][2]

analysis_v2[question_4_1_2] = round(get_class_stdv("4.1"), 1)

### 4.2

In [44]:
#Question 4.2

question_4_2 = dictionary[dictionary["question_id"] == 4.2].reset_index()["question"][0]
analysis_v2[question_4_2] = numerical_data["4.2"]

In [45]:
#Question 4.2 team average
question_4_2_0 = question_shorthand[4.2][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.2"), 1))

analysis_v2[question_4_2_0] = lst_responses

In [46]:
#Question 4.2 class avg
question_4_2_1 = question_shorthand[4.2][1]

analysis_v2[question_4_2_1] = round(get_class_average("4.2"), 1)

In [47]:
#Question 4.2 class std
question_4_2_2 = question_shorthand[4.2][2]

analysis_v2[question_4_2_2] = round(get_class_stdv("4.2"), 1)

### 4.3

In [48]:
#Question 4.3

question_4_3 = dictionary[dictionary["question_id"] == 4.3].reset_index()["question"][0]
analysis_v2[question_4_3] = numerical_data["4.3"]

In [49]:
#Question 4.1 team average
question_4_3_0 = question_shorthand[4.3][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.3"), 1))

analysis_v2[question_4_3_0] = lst_responses

In [50]:
#Question 4.3 class avg
question_4_3_1 = question_shorthand[4.3][1]

analysis_v2[question_4_3_1] = round(get_class_average("4.3"), 1)

In [51]:
#Question 4.3 class std
question_4_3_2 = question_shorthand[4.3][2]

analysis_v2[question_4_3_2] = round(get_class_stdv("4.3"), 1)

### 4.4

In [52]:
#Question 4.4

question_4_4 = dictionary[dictionary["question_id"] == 4.4].reset_index()["question"][0]
analysis_v2[question_4_4] = numerical_data["4.4"]

In [53]:
#Question 4.4 team average
question_4_4_0 = question_shorthand[4.4][0]
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    lst_responses.append(round(get_team_average(student_team_number, "4.4"), 1))

analysis_v2[question_4_4_0] = lst_responses

In [54]:
#Question 4.4 class avg
question_4_4_1 = question_shorthand[4.4][1]

analysis_v2[question_4_4_1] = round(get_class_average("4.4"), 1)

In [55]:
#Question 4.4 class std
question_4_4_2 = question_shorthand[4.4][2]

analysis_v2[question_4_4_2] = round(get_class_stdv("4.4"), 1)

### 5

In [56]:
#Question 5.1-5.6. will need to change this according to how many people are on a team
question_5_1 = dictionary[dictionary["question_id"] == 5.1].reset_index()["question"][0]
question_5_2 = dictionary[dictionary["question_id"] == 5.2].reset_index()["question"][0]
question_5_3 = dictionary[dictionary["question_id"] == 5.3].reset_index()["question"][0]
question_5_4 = dictionary[dictionary["question_id"] == 5.4].reset_index()["question"][0]
#question_5_5 = dictionary[dictionary["question_id"] == 5.5].reset_index()["question"][0]
#question_5_6 = dictionary[dictionary["question_id"] == 5.6].reset_index()["question"][0]

analysis_v2[question_5_1] = full_cleaned_data[["5.1"]]
analysis_v2[question_5_2] = full_cleaned_data[["5.2"]]
analysis_v2[question_5_3] = full_cleaned_data[["5.3"]]
analysis_v2[question_5_4] = full_cleaned_data[["5.4"]]
#analysis_v2[question_5_5] = full_cleaned_data[["5.5"]]
#analysis_v2[question_5_6] = full_cleaned_data[["5.6"]]

In [57]:
#Calculations

#MyPoints
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    student_df = team_df[team_df["TeammateNumber"] == student_teammate_number].reset_index()
    question_needed = '5.' + str(int(student_teammate_number))
    #print(student_df)
    lst_responses.append(student_df[question_needed].reset_index()[question_needed][0])
    
question_5_a = question_shorthand[5][0]
analysis_v2[question_5_a] = lst_responses

In [58]:
#TeammateAvgPoints
lst_responses = []
for student_email in analysis_v2["Email"]:
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == team]["TeammateNumber"])
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    question_needed = '5.' + str(int(student_teammate_number))
    lst_responses.append(round(get_teammates_average(student_team_number, student_teammate_number, question_needed), 1))

question_5_b = question_shorthand[5][1]
analysis_v2[question_5_b] = lst_responses

In [59]:
#ExpectedPoints
lst_responses = []
for student_team_number in analysis_v2["TeamNumber"]:
    team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    lst_responses.append(round(100/team_size, 1))

question_5_c = question_shorthand[5][2]
analysis_v2[question_5_c] = lst_responses

In [60]:
#Percent
question_5_d = question_shorthand[5][3]
analysis_v2[question_5_d] = round((analysis_v2[question_5_b] / analysis_v2[question_5_c]) * 100, 1)

In [61]:
#AveragePointsAllocated
lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    
    temp_q5_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number][["5.1", "5.2", "5.3", "5.4"]]
    temp_q5_df = temp_q5_df.replace({"No Response" : np.nan}).astype(float)
    sum_points = sum(temp_q5_df.reset_index().drop("index", axis=1).iloc[int(student_teammate_number) - 1])
    lst_responses.append(round(sum_points/team_size, 1))

question_5_e = question_shorthand[5][4]
analysis_v2[question_5_e] = lst_responses

In [62]:
#StDevPointsAllocated
lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    
    temp_q5_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number][["5.1", "5.2", "5.3", "5.4"]]
    temp_q5_df = temp_q5_df.replace({"No Response" : np.nan}).astype(float)
    arr = temp_q5_df.reset_index().drop("index", axis=1).dropna().to_numpy().flatten()
    std = np.std(arr[arr != 0])
    lst_responses.append(round(std, 1))

question_5_f = question_shorthand[5][5]
analysis_v2[question_5_f] = lst_responses

In [63]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 1,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 2,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 3,Please allocate 100 points across yourself and your teammates for your contributions to the work of the team. For teammate 4,MyPoints,TeammateAvgPoints,ExpectedPoints,Percent,AveragePointsAllocated,StDevPointsAllocated
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0,6.0,6.3,6.4,0.9,6.0,6.3,...,27,24,24,25,27,32.5,25.0,130.0,25.0,5.4
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0,NaN,6.3,6.4,0.9,NaN,6.3,...,No Response,No Response,No Response,No Response,No Response,21.3,25.0,85.2,NaN,5.4
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0,7.0,6.3,6.4,0.9,7.0,6.3,...,25,25,25,25,25,22.0,25.0,88.0,25.0,5.4
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,6.0,6.3,6.4,0.9,6.0,6.3,...,40,15,20,25,25,25.0,25.0,100.0,25.0,5.4
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0,6.0,6.5,6.4,0.9,6.0,6.2,...,25,25,25,25,25,19.0,25.0,76.0,25.0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,Yousuf Abubakr,yousufabubakr123@berkeley.edu,34.0,4.0,6.0,6.0,6.4,0.9,6.0,6.0,...,25,25,25,25,25,7.5,25.0,30.0,25.0,8.7
129,Avinash Srikanth,avinashsrikanth@berkeley.edu,35.0,1.0,7.0,7.0,6.4,0.9,6.0,6.5,...,25,25,25,25,25,21.3,25.0,85.2,25.0,2.5
130,Ian Bolano,ianpb@berkeley.edu,35.0,2.0,7.0,7.0,6.4,0.9,7.0,6.5,...,24,25,26,25,25,24.0,25.0,96.0,25.0,2.5
131,Nandita Venkataraman,vnandita11@berkeley.edu,35.0,3.0,7.0,7.0,6.4,0.9,7.0,6.5,...,21,23,28,28,28,26.3,25.0,105.2,25.0,2.5
132,Samuel Mankoff,samuel.mankoff@berkeley.edu,35.0,4.0,7.0,7.0,6.4,0.9,6.0,6.5,...,19,24,28,29,29,26.0,25.0,104.0,25.0,2.5

### 6

In [64]:
#Didwellme 

lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    temp_q6_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    response = temp_q6_df[temp_q6_df["TeammateNumber"] == student_teammate_number].reset_index()["6"][0]
    lst_responses.append(response)

question_6_a = question_shorthand[6][0]
analysis_v2[question_6_a] = lst_responses

In [65]:
#DidWell1 thru DidWell6

subset_df = analysis_v2[["TeamNumber", "TeammateNumber", "DidWellMe"]]
#subset_df[subset_df["TeammateNumber"] == 1]
#subset_df

lst_responses_1 = []
lst_responses_2 = []
lst_responses_3 = []
lst_responses_4 = []
#lst_responses_5 = []
#lst_responses_6 = []

for team in subset_df["TeamNumber"]:#.unique():
    team_series = subset_df[subset_df["TeamNumber"] == team].reset_index()["DidWellMe"]
    if len(team_series) == 2:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(np.nan)
        lst_responses_4.append(np.nan)
        #lst_responses_5.append(np.nan)
        #lst_responses_6.append(np.nan)
    if len(team_series) == 3:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(np.nan)
        #lst_responses_5.append(np.nan)
        #lst_responses_6.append(np.nan)
    if len(team_series) == 4:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        #lst_responses_5.append(np.nan)
        #lst_responses_6.append(np.nan)
    if len(team_series) == 5:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        #lst_responses_5.append(team_series[4])
        #lst_responses_6.append(np.nan)
    if len(team_series) == 6:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
       # lst_responses_5.append(team_series[4])
       # lst_responses_6.append(team_series[5])

question_6_b = question_shorthand[6][1]
question_6_c = question_shorthand[6][2]
question_6_d = question_shorthand[6][3]
question_6_e = question_shorthand[6][4]
#question_6_f = question_shorthand[6][5]
analysis_v2[question_6_b] = lst_responses_1
analysis_v2[question_6_c] = lst_responses_2
analysis_v2[question_6_d] = lst_responses_3
analysis_v2[question_6_e] = lst_responses_4
#analysis_v2[question_6_f] = lst_responses_5
#analysis_v2["DidWell6"] = lst_responses_6

### 7

In [66]:
#DoDiffMe
lst_responses = []
for student_email in analysis_v2["Email"]:
    student_team_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeamNumber"][0]
    #team_size = max(analysis_v2[analysis_v2["TeamNumber"] == student_team_number]["TeammateNumber"])
    student_teammate_number = analysis_v2[analysis_v2["Email"] == student_email].reset_index()["TeammateNumber"][0]
    temp_q7_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == student_team_number]
    #temp_q7_df = temp_q7_df.replace({"No Response" : np.nan}).astype(float)
    response = temp_q7_df[temp_q7_df["TeammateNumber"] == student_teammate_number].reset_index()["7"][0]
    lst_responses.append(response)

question_7_a = question_shorthand[7][0]
analysis_v2[question_7_a] = lst_responses

In [67]:
#DoDiff1 thru DoDiff6

subset_df = analysis_v2[["TeamNumber", "TeammateNumber", "DoDiffMe"]]
#subset_df[subset_df["TeammateNumber"] == 1]
#subset_df

lst_responses_1 = []
lst_responses_2 = []
lst_responses_3 = []
lst_responses_4 = []
#lst_responses_5 = []
#lst_responses_6 = []

for team in subset_df["TeamNumber"]:#.unique():
    team_series = subset_df[subset_df["TeamNumber"] == team].reset_index()["DoDiffMe"]
    if len(team_series) == 2:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(np.nan)
        lst_responses_4.append(np.nan)
        #lst_responses_5.append(np.nan)
        #lst_responses_6.append(np.nan)
    if len(team_series) == 3:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(np.nan)
        #lst_responses_5.append(np.nan)
        #lst_responses_6.append(np.nan)
    if len(team_series) == 4:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        #lst_responses_5.append(np.nan)
        #lst_responses_6.append(np.nan)
    if len(team_series) == 5:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
        #lst_responses_5.append(team_series[4])
        #lst_responses_6.append(np.nan)
    if len(team_series) == 6:
        lst_responses_1.append(team_series[0])
        lst_responses_2.append(team_series[1])
        lst_responses_3.append(team_series[2])
        lst_responses_4.append(team_series[3])
       # lst_responses_5.append(team_series[4])
       # lst_responses_6.append(team_series[5])
        
question_7_b = question_shorthand[7][1]
question_7_c = question_shorthand[7][2]
question_7_d = question_shorthand[7][3]
question_7_e = question_shorthand[7][4]
#question_7_f = question_shorthand[7][5]
analysis_v2[question_7_b] = lst_responses_1
analysis_v2[question_7_c] = lst_responses_2
analysis_v2[question_7_d] = lst_responses_3
analysis_v2[question_7_e] = lst_responses_4
#analysis_v2[question_7_f] = lst_responses_5
#analysis_v2["DoDiff6"] = lst_responses_6

### 9

In [68]:
#analysis_v2[question_shorthand[9.1]] = full_cleaned_data["9.1"]
#analysis_v2[question_shorthand[9.2]] = full_cleaned_data["9.2"]
#analysis_v2[question_shorthand[9.3]] = full_cleaned_data["9.3"]

### 10 (not used here but can use functions below)

In [69]:
#analysis_v2[question_shorthand[10.1][0]] = get_class_average("10.1")
#analysis_v2[question_shorthand[10.1][1]] = get_class_stdv("10.1")

#analysis_v2[question_shorthand[10.2][0]] = get_class_average("10.2")
#analysis_v2[question_shorthand[10.2][1]] = get_class_stdv("10.2")

#analysis_v2[question_shorthand[10.3][0]] = get_class_average("10.3")
#analysis_v2[question_shorthand[10.3][1]] = get_class_stdv("10.3")

### 11

In [70]:
#question_11 = dictionary[dictionary["question_id"] == 11].reset_index()["question"][0]
#analysis_v2[question_11] = full_cleaned_data["11"]

### 12

In [71]:
#question_12 = dictionary[dictionary["question_id"] == 12].reset_index()["question"][0]
#analysis_v2[question_12] = full_cleaned_data["12"]

### 14

In [72]:
#14.1 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '14.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_14_me = question_shorthand[14][0]
analysis_v2[question_14_me] = lst_responses

In [73]:
analysis_v2.head()

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,DidWell1,DidWell2,DidWell3,DidWell4,DoDiffMe,DoDiff1,DoDiff2,DoDiff3,DoDiff4,ContributeMe
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0,6.0,6.3,6.4,0.9,6.0,6.3,...,No Response,No Response,Communicate what work needs to be done,Tracking Progress,No Response,No Response,No Response,Work on deadlines sooner,Work Allocation,No Response
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0,NaN,6.3,6.4,0.9,NaN,6.3,...,No Response,No Response,Communicate what work needs to be done,Tracking Progress,No Response,No Response,No Response,Work on deadlines sooner,Work Allocation,No Response
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0,7.0,6.3,6.4,0.9,7.0,6.3,...,No Response,No Response,Communicate what work needs to be done,Tracking Progress,Work on deadlines sooner,No Response,No Response,Work on deadlines sooner,Work Allocation,I think I did well in some technical aspects o...
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,6.0,6.3,6.4,0.9,6.0,6.3,...,No Response,No Response,Communicate what work needs to be done,Tracking Progress,Work Allocation,No Response,No Response,Work on deadlines sooner,Work Allocation,Contributes Well
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0,6.0,6.5,6.4,0.9,6.0,6.2,...,communicating,We are doing well at comunicating at the end o...,Better communication,We definitely met our milestones in a timely m...,Plan things out more,Plan things out more,I would like us to be more proactive about dea...,Better work distribution plannjng,I wish we had done manufacturing earlier,contributing to work

In [74]:
#14

question_14_1 = question_shorthand[14][1]
question_14_2 = question_shorthand[14][2]
question_14_3 = question_shorthand[14][3]
question_14_4 = question_shorthand[14][4]
#question_14_5 = question_shorthand[14][5]
#question_14_6 = question_shorthand[14][6]

feedback_1 = []
feedback_2 = []
feedback_3 = []
feedback_4 = []
#feedback_5 = [] 
#feedback_6 = []#need to adjust to max team size

#possibilities = ["14.1", "14.2", "14.3", "14.4", "14.5", "14.6"]
for i in range(len(full_cleaned_data)):
    my_teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    my_team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_number_str = str(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == my_team_number]
    list_feedback_for_me = list(my_team_df["14." + str(my_teammate_number)])
    num_teammates = len(list_feedback_for_me)
    extra_needed = 4 - num_teammates
    placeholders = [''] * extra_needed
    all_feedback = list_feedback_for_me + placeholders

    feedback_1.append(all_feedback[0])
    feedback_2.append(all_feedback[1])
    feedback_3.append(all_feedback[2])
    feedback_4.append(all_feedback[3])
    #feedback_5.append(all_feedback[4])
    #feedback_6.append(all_feedback[5])
    
analysis_v2[question_14_1] = feedback_1
analysis_v2[question_14_2] = feedback_2
analysis_v2[question_14_3] = feedback_3
analysis_v2[question_14_4] = feedback_4
#analysis_v2[question_14_5] = feedback_5
#analysis_v2[question_14_6] = feedback_6

In [75]:
analysis_v2.head()

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,DoDiffMe,DoDiff1,DoDiff2,DoDiff3,DoDiff4,ContributeMe,Contribute1,Contribute2,Contribute3,Contribute4
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0,6.0,6.3,6.4,0.9,6.0,6.3,...,No Response,No Response,No Response,Work on deadlines sooner,Work Allocation,No Response,No Response,No Response,Did amazing manufacturing work,Great Manufacturing Skills
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0,NaN,6.3,6.4,0.9,NaN,6.3,...,No Response,No Response,No Response,Work on deadlines sooner,Work Allocation,No Response,No Response,No Response,Great drawings and work on our reports,Starts Documents
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0,7.0,6.3,6.4,0.9,7.0,6.3,...,Work on deadlines sooner,No Response,No Response,Work on deadlines sooner,Work Allocation,I think I did well in some technical aspects o...,No Response,No Response,I think I did well in some technical aspects o...,Contributes Well
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,6.0,6.3,6.4,0.9,6.0,6.3,...,Work Allocation,No Response,No Response,Work on deadlines sooner,Work Allocation,Contributes Well,No Response,No Response,Keeping our team on track and good report work,Contributes Well
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0,6.0,6.5,6.4,0.9,6.0,6.2,...,Plan things out more,Plan things out more,I would like us to be more proactive about dea...,Better work distribution plannjng,I wish we had done manufacturing earlier,contributing to work,contributing to work,Ashley is good at the write ups and organization,Did great job with tolerating tables,Assisted with designing the Business Pitches a...

### 15

In [76]:
#15.1 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '15.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_15_me = question_shorthand[15][0]
analysis_v2[question_15_me] = lst_responses

In [77]:
#15

question_15_1 = question_shorthand[15][1]
question_15_2 = question_shorthand[15][2]
question_15_3 = question_shorthand[15][3]
question_15_4 = question_shorthand[15][4]
#question_15_5 = question_shorthand[15][5]
#question_15_6 = question_shorthand[15][6]

feedback_1 = []
feedback_2 = []
feedback_3 = []
feedback_4 = []
#feedback_5 = [] 
#feedback_6 = []#need to adjust to max team size

#possibilities = ["14.1", "14.2", "14.3", "14.4", "14.5", "14.6"]
for i in range(len(full_cleaned_data)):
    my_teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    my_team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_number_str = str(full_cleaned_data.iloc[i]["TeamNumber"])
    my_team_df = full_cleaned_data[full_cleaned_data["TeamNumber"] == my_team_number]
    list_feedback_for_me = list(my_team_df["15." + str(my_teammate_number)])
    num_teammates = len(list_feedback_for_me)
    extra_needed = 4 - num_teammates
    placeholders = [''] * extra_needed
    all_feedback = list_feedback_for_me + placeholders

    feedback_1.append(all_feedback[0])
    feedback_2.append(all_feedback[1])
    feedback_3.append(all_feedback[2])
    feedback_4.append(all_feedback[3])
    #feedback_5.append(all_feedback[4])
    #feedback_6.append(all_feedback[5])
    
analysis_v2[question_15_1] = feedback_1
analysis_v2[question_15_2] = feedback_2
analysis_v2[question_15_3] = feedback_3
analysis_v2[question_15_4] = feedback_4
#analysis_v2[question_15_5] = feedback_5
#analysis_v2[question_15_6] = feedback_6

### 16

In [78]:

#16 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '16.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_16_me = question_shorthand[16][0]
analysis_v2[question_16_me] = lst_responses

In [79]:
#Question 16 team average
question_16_tm_avg = question_shorthand[16][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '16.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_16_tm_avg] = lst_responses

In [80]:
#Question 16 class avg
question_16_class_avg = question_shorthand[16][2]
class_avg = np.nanmean(full_cleaned_data[["16.1", "16.2", "16.3", "16.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_16_class_avg] = round(class_avg, 1)

In [81]:
#Question 16 class std
question_16_class_std = question_shorthand[16][3]
class_std_arr = full_cleaned_data[["16.1", "16.2", "16.3", "16.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_16_class_std] = round(np.std(class_std_arr_no_na), 1)

### 17

In [82]:
#17 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '17.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_17_me = question_shorthand[17][0]
analysis_v2[question_17_me] = lst_responses

In [83]:
#Question 17 team average
question_17_tm_avg = question_shorthand[17][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '17.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_17_tm_avg] = lst_responses

In [84]:
#analysis_v2

In [85]:
#Question 17 class avg
question_17_class_avg = question_shorthand[17][2]
class_avg = np.nanmean(full_cleaned_data[["17.1", "17.2", "17.3", "17.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_17_class_avg] = round(class_avg, 1)

In [86]:
#Question 17 class std
question_17_class_std = question_shorthand[17][3]
class_std_arr = full_cleaned_data[["17.1", "17.2", "17.3", "17.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_17_class_std] = round(np.std(class_std_arr_no_na), 1)

### 18

In [87]:
#18 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '18.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_18_me = question_shorthand[18][0]
analysis_v2[question_18_me] = lst_responses

In [88]:
#Question 18 team average
question_18_tm_avg = question_shorthand[18][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '18.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_18_tm_avg] = lst_responses

In [89]:
#Question 18 class avg
question_18_class_avg = question_shorthand[18][2]
class_avg = np.nanmean(full_cleaned_data[["18.1", "18.2", "18.3", "18.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_18_class_avg] = round(class_avg, 1)

In [90]:
#Question 18 class std
question_18_class_std = question_shorthand[18][3]
class_std_arr = full_cleaned_data[["18.1", "18.2", "18.3", "18.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_18_class_std] = round(np.std(class_std_arr_no_na), 1)

### 19

In [91]:
#19 (me)

lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    question_needed = '19.' + str(teammate_number)
    lst_responses.append(full_cleaned_data.iloc[i][question_needed])

question_19_me = question_shorthand[19][0]
analysis_v2[question_19_me] = lst_responses

In [92]:
#Question 19 team average
question_19_tm_avg = question_shorthand[19][1]
lst_responses = []

for i in range(len(full_cleaned_data)):
    teammate_number = int(full_cleaned_data.iloc[i]["TeammateNumber"])
    team_number = int(full_cleaned_data.iloc[i]["TeamNumber"])
    question_needed = '19.' + str(teammate_number)
    lst_responses.append(round(get_teammates_average(team_number, teammate_number, question_needed), 1))

analysis_v2[question_19_tm_avg] = lst_responses

In [93]:
#Question 19 class avg
question_19_class_avg = question_shorthand[19][2]
class_avg = np.nanmean(full_cleaned_data[["19.1", "19.2", "19.3", "19.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten())
analysis_v2[question_19_class_avg] = round(class_avg, 1)

In [94]:
#Question 19 class std
question_19_class_std = question_shorthand[19][3]
class_std_arr = full_cleaned_data[["19.1", "19.2", "19.3", "19.4"]].replace({"No Response" : np.nan}).astype(float).to_numpy().flatten()
class_std_arr_no_na = class_std_arr[~np.isnan(class_std_arr)]
analysis_v2[question_19_class_std] = round(np.std(class_std_arr_no_na), 1)

## Add extra questions

In [95]:
full_cleaned_data.columns

Index(['index', 'Unnamed: 0', 'Email', 'TeamNumber', 'TeammateNumber',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail', '33',
       '39.1', '39.2', '39.3', '2.1', '2.2', '2.3', '3', '4.1', '4.2', '4.3',
       '4.4', '5.1', '5.2', '5.3', '5.4', '6', '7', '38.1', '38.2', '38.3',
       '14.1', '14.2', '14.3', '14.4', '15.1', '15.2', '15.3', '15.4', '16.1',
       '16.2', '16.3', '16.4', '17.1', '17.2', '17.3', '17.4', '18.1', '18.2',
       '18.3', '18.4', '19.1', '19.2', '19.3', '19.4', '55', '51', '52', '53',
       '54'],
      dtype='object')

In [98]:

analysis_v2[question_shorthand[38.1]] = full_cleaned_data["38.1"]
analysis_v2[question_shorthand[38.2]] = full_cleaned_data["38.2"]
analysis_v2[question_shorthand[38.3]] = full_cleaned_data["38.3"]
analysis_v2["Q33"] = full_cleaned_data['33']
#analysis_v2["What did you learn from the first check-in survey feedback?"] = full_cleaned_data['57']
#analysis_v2["Q33_TEXT"] = full_cleaned_data['33.4.TEXT']
#analysis_v2["Q25"] = full_cleaned_data['25']

In [99]:
analysis_v2

,FullName,Email,TeamNumber,TeammateNumber,Our team is clear about the shared goals for our work together,SharedGoalTeamAvg,SharedGoalClassAvg,SharedGoalClassStDev,We each know about one another's individual goals for our work together,IndvGoalTeamAvg,...,ExpertiseClassAvg,ExpertiseClassStDev,RespectMe,RespectTeammateAvg,RespectClassAvg,RespectClassStDev,ImproveAmt1,ImproveAmt2,ImproveAmt3,Q33
0,Allan Zhong,allanzhong@berkeley.edu,1.0,1.0,6.0,6.3,6.4,0.9,6.0,6.3,...,6.5,0.8,6.0,5.0,6.5,0.7,Moderately better,Moderately better,Moderately better,Yes
1,Edwin Lopez,eclopez19@berkeley.edu,1.0,2.0,NaN,6.3,6.4,0.9,NaN,6.3,...,6.5,0.8,No Response,5.3,6.5,0.7,No Response,No Response,No Response,No Response
2,Jerrick Wang,jerrick@berkeley.edu,1.0,3.0,7.0,6.3,6.4,0.9,7.0,6.3,...,6.5,0.8,7.0,5.0,6.5,0.7,Much better,Moderately better,Moderately better,Yes
3,Simran Kaur Khahira,simrankk@berkeley.edu,1.0,4.0,6.0,6.3,6.4,0.9,6.0,6.3,...,6.5,0.8,5.0,6.5,6.5,0.7,About the same,Moderately better,Slightly better,Yes
4,Ashley De Jesus,adejesus22@berkeley.edu,2.0,1.0,6.0,6.5,6.4,0.9,6.0,6.2,...,6.5,0.8,6.0,6.3,6.5,0.7,Moderately better,Moderately better,Moderately better,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,Yousuf Abubakr,yousufabubakr123@berkeley.edu,34.0,4.0,6.0,6.0,6.4,0.9,6.0,6.0,...,6.5,0.8,6.0,6.5,6.5,0.7,About the same,About the same,About the same,Yes
129,Avinash Srikanth,avinashsrikanth@berkeley.edu,35.0,1.0,7.0,7.0,6.4,0.9,6.0,6.5,...,6.5,0.8,6.0,6.3,6.5,0.7,About the same,Moderately better,About the same,Yes
130,Ian Bolano,ianpb@berkeley.edu,35.0,2.0,7.0,7.0,6.4,0.9,7.0,6.5,...,6.5,0.8,7.0,6.3,6.5,0.7,Much better,Much better,Much better,Yes
131,Nandita Venkataraman,vnandita11@berkeley.edu,35.0,3.0,7.0,7.0,6.4,0.9,7.0,6.5,...,6.5,0.8,7.0,6.3,6.5,0.7,Much better,Much better,Much better,Yes
132,Samuel Mankoff,samuel.mankoff@berkeley.edu,35.0,4.0,7.0,7.0,6.4,0.9,6.0,6.5,...,6.5,0.8,6.0,6.7,6.5,0.7,Much better,Much better,Much better,Yes

In [100]:
analysis_v2.to_csv("E29_CHECKIN3_MACROANALYSIS_V1.csv")